\import Algebra.Meta
\import Category
\import Category.Functor
\import Category.Limit
\import Category.Slice
\import Category.Subcat
\import Category.Topos.Presheaf
\import Category.Topos.Sheaf.Site
\import Equiv
\import Function (IsInj, IsSurj)
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Topology.Locale
\open PresieveMatchingFamily (matchingFamily)

\record MatchingFamily.{s,o1,h1,o2,h2} {C : Site.{o1,h1}} {D : Precat.{o2,h2}} (F : Functor C.op D) {J : \Type s} (x : C) (P : J -> ObOver x) (d : D)
  | \coerce family (j : J) : Hom d (F (P j).1)
  | isMatching {j j' : J} {z : C} (g : Hom z (P j).1) (g' : Hom z (P j').1) : (P j).2 ∘ g = (P j').2 ∘ g' -> F.Func g ∘ family j = F.Func g' ∘ family j'
  \where {
    \func matchingFamily.{s,o1,h1,o2,h2} {C : Site.{o1,h1}} {D : Precat.{o2,h2}} (F : Functor C.op D) {J : \Type s} (x : C) (P : J -> ObOver x) (d : D) (h : Hom d (F x)) : MatchingFamily F x P d \cowith
      | family j => Func (P j).2 ∘ h
      | isMatching g g' gg' => inv o-assoc *> pmap (`∘ h) (inv Func-o *> pmap Func (later gg') *> Func-o) *> o-assoc

    \protected \func map.{s,o1,h1,o2,h2} {C : Site.{o1,h1}} {D : Precat.{o2,h2}} (F : Functor C.op D) {I J : \Type s} (f : I -> J) {x : C} (P : J -> ObOver x) (d : D) (mf : MatchingFamily F x P d) : MatchingFamily F x (\lam i => P (f i)) d \cowith
      | family i => mf (f i)
      | isMatching => isMatching
      \where {
        \lemma isEquiv (fs : IsSurj f) : IsEquiv (map F f P d)
          => IsEquiv.fromInjSurj (\lam p => exts \lam j => \case \elim j, fs j \with {
            | _, inP (i,idp) => path (p __ i)
          }) \lam mf =>
            \let t j => TruncP.rec-set {_} {Hom d (F (P j).1) } (fs j) (\lam s => Func (C.idtoiso $ pmap (\lam x => (P x).1) $ inv s.2).f ∘ mf s.1)
              \lam s s' => mf.isMatching _ _ $ inv (ObOver.unequals (pmap P (inv s.2))) *> ObOver.unequals (pmap P (inv s'.2))
            \in inP (\new MatchingFamily {
              | family j => (t j).1
              | isMatching {j} {j'} g g' gg' => \case (t j).2, (t j').2 \with {
                | inP (s,sp), inP (s',s'p) =>
                  \have aux => mf.isMatching ((C.idtoiso $ pmap (\lam x => (P x).1) (inv s.2)).f ∘ g) ((C.idtoiso $ pmap (\lam x => (P x).1) (inv s'.2)).f ∘ g') $ inv o-assoc *> pmap (`∘ _) (inv $ ObOver.unequals (pmap P (inv s.2))) *> gg' *> pmap (`∘ _) (ObOver.unequals (pmap P (inv s'.2))) *> o-assoc
                  \in pmap (_ ∘) (inv sp) *> inv o-assoc *> pmap (`∘ _) (inv Func-o) *> aux *> pmap (`∘ _) Func-o *> o-assoc *> pmap (_ ∘) s'p
              }
            }, exts \lam i => TruncP.rec-set-eval (later (i,idp)) *> pmap (`∘ _) (later Func-id) *> id-left)
      }
  }

\func PresieveMatchingFamily.{o1,h1,o2,h2} {C : Site.{o1,h1}} {D : Precat.{o2,h2}} (F : Functor C.op D) (x : C) (P : Presieve x) (d : D)
  => MatchingFamily F {Given P} x __.1 d
  \where {
    \func matchingFamily.{o1,h1,o2,h2} {C : Site.{o1,h1}} {D : Precat.{o2,h2}} (F : Functor C.op D) (x : C) (P : Presieve x) (d : D) (h : Hom d (F x)) : PresieveMatchingFamily F x P d
      => MatchingFamily.matchingFamily F {Given P} x __.1 d h
  }

\func IsSeparatedPresheaf.{o2,h2,o1,h1} {C : Site.{o1,h1}} {D : Precat.{o2,h2}} (F : Functor C.op D)
  => ∀ {x : C} ∀ {S : isCover x} (d : F.D) {h h' : Hom d (F x)} (∀ {y : S} (F.Func y.2 ∘ h = F.Func y.2 ∘ h') -> h = h')
  \where {
    \protected \lemma char : IsSeparatedPresheaf F <-> ∀ {x : C} ∀ {S : isCover x} (d : F.D) (IsInj {_} {PresieveMatchingFamily F x S d} (matchingFamily F x S d))
      => (\lam Fs {x} {S} Sc d hh' => Fs Sc d \lam {y} Sy => pmap {PresieveMatchingFamily F x S d} (family {__} (y,Sy)) hh',
          \lam Fs Sc d hh' => Fs Sc d $ exts \lam j => hh' j.2)
  }

\func IsSheaf.{o2,h2,o1,h1} {C : Site.{o1,h1}} {D : Precat.{o2,h2}} (F : Functor C.op D)
  => ∀ {x : C} ∀ {S : isCover x} (d : F.D) (IsEquiv {_} {PresieveMatchingFamily F x S d} (matchingFamily F x S d))

-- | Sheaves valued in {D}
\class VSheaf.{s,o,h} \extends VPresheaf.{o,h,s,s} {
  \override C : Site.{s,s}
  | isSheaf : IsSheaf F

  \lemma isSeparated : IsSeparatedPresheaf \this.F
    => IsSeparatedPresheaf.char.2 \lam Sc d => IsEquiv.isInj (isSheaf Sc d)

  \lemma direct_image.{s',o',h'} {C' : Site.{s',s'}} (f : SiteHom C' C) : VSheaf D C' (Comp F f.op) \cowith
    | isSheaf {x} {S} xS d => IsEquiv.trans (isSheaf (f.Func-cover xS) d) $
        IsEquiv.trans (MatchingFamily.map.isEquiv {C} {D} {F} {Given S} {Given (py : ObOver (f x)) ∃ (px : S) (py = (f px.1, Func px.2))} {\lam s => (_, inP (s.1,s.2,idp))} \lam (_, inP (px,Spx,idp)) => inP ((px,Spx),idp)) $
        inP \new QEquiv {
          | f mf => \new MatchingFamily {
            | family => mf.family
            | isMatching {j} {j'} g g' gg' => mf.isMatching (Func g) (Func g') $ inv Func-o *> pmap Func gg' *> Func-o
          }
          | ret mf => \new MatchingFamily {
            | family => mf.family
            | isMatching {j} {j'} g g' gg' => \case f.Func-flat j.1.2 j'.1.2 g g' gg' \with {
              | inP (w,s1,s2,s1s2,h,s1h,s2h) => rewrite (inv s1h, inv s2h, F.Func-o, F.Func-o) $ o-assoc *> pmap (_ ∘) (mf.isMatching s1 s2 s1s2) *> inv o-assoc
            }
          }
          | ret_f => idpe
          | f_sec => idpe
        }
} \where {
  \func restrict.{s,o,h} {L : Locale.{s}} (a : L) (S : VSheaf.{s,o,h} { | C => L }) : VSheaf S.D (L.restrict a) \cowith
    | F => Comp S Locale.restrict.functor.op
    | isSheaf => {?} -- TODO[sorts]

  \lemma direct_image_locale.{s,o,h,o',h'} {L L' : Locale.{s}} (f : FrameHom L' L) (S : VSheaf.{s,o,h} { | C => L }) : VSheaf S.D L' (Comp S f.functor.op)
    => S.direct_image f.functor

  \func direct_image_id.{s,o,h} {C : Site.{s,s}} (S : VSheaf.{s,o,h} { | C => C }) : S.direct_image SiteHom.id = {VSheaf S.D C} S
    => ext $ ext (idp, ext \lam h => idp)

  \func transport_direct_image.{s,o,h} {L L' : Locale.{s}} (p : L = L') (S : VSheaf.{s,o,h} { | C => L }) : transport (VSheaf S.D) p S = direct_image_locale (Iso.f {Precat.idtoiso p}) S \elim p
    | idp => inv (direct_image_id S)

  \func transport_direct_image-iso.{s,o,h} {L L' : Locale.{s}} (e : Iso {LocaleCat} {L} {L'}) (S : VSheaf.{s,o,h} { | C => L }) : transport (VSheaf S.D) (Cat.isotoid e) S = direct_image_locale e.f S
    => transport_direct_image (Cat.isotoid e) S *> path \lam i => direct_image_locale (IsEquiv.f_ret univalence {e} i).f S
}

\instance VSheafCat.{s,v} (D : Cat.{\suc v, v}) (C : Site.{s,s}) : Cat
  => subCat {VPresheafCat D C} {VSheaf D C} (\new Embedding {
    | f P => P
    | isEmb _ _ => \new Retraction {
      | sec p => ext VSheaf { | VPresheaf => p }
      | f_sec => idpe
    }
  })

-- | Sheaves valued in sets
\class Sheaf.{s,v} \extends Presheaf.{v,s,s}, VSheaf.{s, \suc v, v}

\lemma sheafOnPresentedFrame.{s,o,h} {P : FramePres.{s}} {D : CompleteCat.{s,o,h}} (F : VSheaf D (FramePresSite P)) : VSheaf D (PresentedFrame P) extend \cowith
  | isSheaf => {?}
  {-
  | isSheaf {U} {S : Sieve} (inP (J, g, U<=g, g<=s)) =>
    \new Limit {
      | isLimit z =>
        \have | lim (j : \Sigma (x : P) (embed x <= U)) => cover-lem (U<=g (j.2 (cover-inj () idp)))
              | lem (j : \Sigma (x : P) (embed x <= U)) (k : \Sigma (y : \Sigma (y : P) (Cover1 y j.1)) (∃ (j : \Sigma (j : J) (x : P) ((g j).1.1 x)) (Cover1 y.1 j.2))) : S (\lam d => j.2 (cover-trans d (\lam _ => k.1.2))) => \case k.2 \with {
                | inP ((j,z,z<=gj),y<=z) => transport (S __) prop-pi (S.isSieve {embed k.1.1} (\lam {w} w<=y => (g j).1.2 w (cover-trans w<=y \lam _ => cover-trans y<=z \lam _ => cover-inj (z,z<=gj) idp)) (g<=s j))
              }
        \in inP \new QEquiv {
          | ret (c : Cone) =>
            \have cone j => \new Cone (lim j).G z {
              | coneMap k => extend-proj k.1.1 ∘ c.coneMap ((embed k.1.1, \lam z<=y => j.2 (cover-trans z<=y (\lam _ => k.1.2))), lem j (k.1,k.2))
              | coneCoh h => inv o-assoc *> pmap (`∘ _) (inv (extend-proj-nat h.1 (cover-trans __ (\lam _ => h.1)))) *> o-assoc *> pmap (_ ∘) (c.coneCoh (later (cover-trans __ (\lam _ => h.1), prop-pi)))
            }
            \in (extend.lim U).limMap \new Cone {
              | coneMap j => (lim j).limMap (cone j)
              | coneCoh {j} {j'} h => (lim j').limUnique \lam k => inv o-assoc *> pmap (`∘ _) (inv Func-o) *> (lim j).limBeta (cone j) ((k.1.1, (FramePresPreorder P).<=-transitive k.1.2 h), k.2) *>
                                                                                                              path (\lam i => extend-proj k.1.1 ∘ c.coneMap ((embed k.1.1, prop-pi i), pathOver prop-pi i)) *> inv ((lim j').limBeta (cone j') k)
            }
          | ret_f h => limUnique \lam j => (extend.lim S.cone.apex).limBeta _ j *> (lim j).limUnique (\lam k => later $ (lim j).limBeta _ k *> inv o-assoc *>
                                                                                                                                               pmap (`∘ h) (extend-proj-nat' _ *> inv (coneCoh {_} {j} {later (k.1.1, \lam d => j.2 (cover-trans d (\lam _ => k.1.2)))} $ later k.1.2)) *> o-assoc)
          | f_sec (c : Cone) => exts \lam m => limUnique \lam j =>
            inv o-assoc *> pmap (`∘ _) (extend-proj-nat'' m.1.2 _) *> (extend.lim U).limBeta _ (j.1, <=-transitive j.2 m.1.2) *> (lim (j.1, <=-transitive j.2 m.1.2)).limUnique \lam k =>
                (lim (j.1, <=-transitive j.2 m.1.2)).limBeta _ k *> pmap (_ ∘) (inv (c.coneCoh (\lam d => j.2 (cover-trans d (\lam _ => k.1.2)), prop-pi))) *>
                                                                    inv o-assoc *> pmap (`∘ _) (coneMap-nat (\lam d => j.2 (cover-trans d (\lam _ => k.1.2))) {k.1.1, \lam d => d} {j} k.1.2) *> o-assoc
        }
    }
    -}
  \where {
    \open PresentedFrame(embed)
    \open Limit
    \open Cover

{-
    \lemma genSieve.{s} {P : FramePres.{s}} (a : P) {J : \Set s} (g : J -> P) : Sieve {FramePresPreorder P} a (\lam {b} _ => ∃ (j : J) (Cover1 b (g j))) \cowith
      | isSieve {z} {y} z<=y (inP (j,y<=gj)) => inP (j, cover-trans z<=y (\lam _ => y<=gj))

    \lemma cover1-lem.{s,o,h} {P : FramePres.{s}} {D : CompleteCat.{s,o,h}} {F : VSheaf D (FramePresSite P)} {a : P} {J : \Set s} {g : J -> P} (j : J) (p : Cover1 a (g j))
      : Limit { | Cone => Cone.map F (Presieve.cone {genSieve a g}) }
      => Presieve.idLimit (genSieve a g) (inP (later (j,p)))

    \lemma cover'-lem.{s,o,h} {P : FramePres.{s}} {D : CompleteCat.{s,o,h}} {F : VSheaf D (FramePresSite P)} {a b : P} (b<=a : Cover1 b a) {J : \Set s} {g : J -> P} (c : Cover' a g)
      : Limit { | Cone => Cone.map F (Presieve.cone {genSieve b g}) } \elim c
      | cover-basic' {x} {y} p {f} c q => F.isSheaf {b} {genSieve b g} (inP (J,
                                                                             \lam j => (conj b (g j), cover-proj1 idp () idp),
                                                                             inP (y, cover-trans b<=a (\lam _ => cover-proj2 p () idp), f, c, \lam j => (cover-trans (cover-proj2 idp () idp) (\lam _ => cover-proj2 (q j) () idp),
                                                                                                                                                         cover-prod (cover-proj1 idp () idp) (transportInv (Cover1 _) (q j) (cover-prod (cover-trans (cover-proj1 idp () idp) (\lam _ => cover-trans b<=a (\lam _ => cover-proj1 p () idp))) (cover-proj2 idp () idp))))),
                                                                             \lam j => inP (j, cover-proj2 idp () idp)))
      | cover-inj' j p => cover1-lem j (cover-trans b<=a (\lam _ => cover-inj () p))
      | cover-trans' {_} {f} c d => Presieve.transLimit (genSieve b f) (genSieve b g) (\lam {x} x<=b => cover'-lem (cover-trans x<=b (\lam _ => b<=a)) c) (\lam {x} {x<=b} (inP (i,s)) => cover'-lem s (d i))
      | cover-proj1-inj' p j q => cover1-lem j $ cover-trans b<=a \lam _ => cover-proj1 p () q
      | cover-proj2-inj' p j q => cover1-lem j $ cover-trans b<=a \lam _ => cover-proj2 p () q
      | cover-prod-inj' {x} {y} c1 c2 j p => cover1-lem j $ cover-trans b<=a \lam _ => Cover'.cover'-cover (cover-prod-inj' c1 c2 () p)

    \lemma cover-lem.{s,o,h} {P : FramePres.{s}} {D : CompleteCat.{s,o,h}} {F : VSheaf D (FramePresSite P)} {a : P} {J : \Set s} {g : J -> P} (c : Cover a g)
      => cover'-lem (cover-inj () idp) (Cover'.cover-cover' c)
-}

    \func extend : Functor (PresentedFrame P).op D \cowith
      | F b => lim b
      | Func {a} {b} b<=a => limMap {lim b} (cone b<=a)
      | Func-id {b} => (lim b).limUniqueBeta {lim b} \lam j => unfold $ inv $ id-right *> cong (ext idp)
      | Func-o {a} {b} {c} {b<=c} {a<=b} => (lim c).limUniqueBeta {lim a} \lam j => inv (pmap (`∘ _) ((lim c).limBeta (cone b<=c) j) *> (lim b).limBeta (cone a<=b) (j.1, j.2 <=∘ b<=c)) *> o-assoc
      \where {
        \func limFunctor (b : PresentedFrame P)
          => Comp F (subPrecat.embedding \lam (t : \Sigma (x : P) (PresentedFrame.embed x <= b)) => t.1).op

        \func lim (b : PresentedFrame P)
          => D.limit (limFunctor b)

        \func cone {a b : PresentedFrame P} (b<=a : b <= a) : Cone (limFunctor b) (lim a) \cowith
          | coneMap (x,x<=b) => coneMap (later (x, (\lam {_} => x<=b) <=∘ b<=a))
          | coneCoh {j} {j'} => \case \elim j, \elim j' \with { | (_,_), (_,_) => \lam h => coneCoh $ later h }
      }

{-
    \func extend-proj (y : P) : Hom (extend (embed y)) (F y)
      => coneMap $ later (y, \lam d => d)

    \lemma extend-proj-nat'' {U V : PresentedFrame P} (U<=V : U <= V) {x : P} (x<=U : embed x <= U)
      : coneMap (later (x,x<=U)) ∘ extend.Func U<=V = coneMap (later (x, <=-transitive x<=U U<=V))
      => (extend.lim U).limBeta (\new Cone {
        | coneMap j => (extend.lim V).coneMap (j.1, <=-transitive j.2 U<=V)
        | coneCoh {j} {j'} => \case \elim j, \elim j' \with { | (_,_), (_,_) => \lam h => coneCoh $ later h }
      }) (x,x<=U)

    \lemma coneMap-nat {U V : PresentedFrame P} (h' : U <= V) {a : \Sigma (x : P) (embed x <= U)} {b : \Sigma (y : P) (embed y <= V)} (h : Cover1 a.1 b.1)
      : (extend.lim U).coneMap a ∘ extend.Func h' = F.F.Func h ∘ (extend.lim V).coneMap b
      => extend-proj-nat'' h' a.2  *> inv ((extend.lim V).coneCoh {b} {a.1, <=-transitive a.2 h'} h)

    \lemma extend-proj-nat' {y : P} {V : PresentedFrame P} (h' : embed y <= V)
      : extend-proj y ∘ extend.Func h' = coneMap (later (y,h'))
      => extend-proj-nat'' h' (\lam d => d) *> path (\lam i => coneMap (later (y, prop-pi i)))

    \lemma extend-proj-nat {y z : P} (h : Cover1 y z) (h' : embed y <= embed z)
      : extend-proj y ∘ extend.Func h' = F.F.Func h ∘ extend-proj z
      => extend-proj-nat' h' *> inv (coneCoh $ later h)
      -}
  }

\lemma sheaf-reflect.{s,o,h} {C : Site.{s}} {D E : Cat.{o,h}} (G : Functor D E)
                             (G-lim : \Pi {J : Precat.{s,s}} (H : Functor J D) -> ReflectsLimit G H) (F : Functor C.op D) (S : VSheaf E C (Comp G F)) : VSheaf D C F \cowith
  | isSheaf Sc d => {?}
  -- TODO[sorts]: | isSheaf {x} {s : Sieve x} c => G-lim (Comp F s.diagram.op) (Cone.map F s.cone) (S.isSheaf c)

{-
\lemma sheaf-preserve.{s,o,h} {C : Site.{s}} {D E : Cat.{o,h}} (G : Functor D E)
                              (G-lim : \Pi {J : Precat.{s,s}} (H : Functor J D) -> PreservesLimit G H) (F : VSheaf D C) : VSheaf E C (Comp G F) \cowith
  | isSheaf {x} {s : Sieve x} c => G-lim (Comp F s.diagram.op) (F.isSheaf c)

\lemma vsheafOnSiteWithBasis-equalizer {C : SiteWithBasis} {D : CompleteCat.{\suc \lp}} (F : Functor C.op D)
  (p : \Pi (x : C) {J : \Set} (g : J -> ObOver x) (c : isBasicCover x g) -> Equalizer (leftMap x g) (rightMap x g) (F x) (eqMap x g))
  : VSheaf D C F
  => vsheafOnSiteWithBasis F \lam x {J} g c z =>
      \let | P1 => product1 x g
           | P2 => product2 x g
           | t (c : \Sigma (h : Hom z _) (leftMap x g ∘ h = rightMap x g ∘ h)) => \new MatchingFamily x g z {
             | family j => P1.proj j ∘ c.1
             | isMatching j j' => inv o-assoc *> pmap (`∘ c.1) (inv (tupleBeta {P2})) *> o-assoc *> pmap (P2.proj (j,j') ∘) c.2 *> inv o-assoc *> pmap (`∘ c.1) (tupleBeta {P2}) *> o-assoc
           }
           | e => inP \new QEquiv t {
             | ret (m : MatchingFamily x g z) => (tupleMap m.family, tupleEq \lam j => inv o-assoc *> pmap (`∘ _) (tupleBeta {P2}) *> o-assoc *> pmap (_ ∘) (tupleBeta {P1}) *> m.isMatching j.1 j.2 *> inv (pmap (`∘ _) (tupleBeta {P2}) *> o-assoc  *> pmap (_ ∘) (tupleBeta {P1})) *> o-assoc)
             | ret_f c => ext (Product.tupleEta {P1})
             | f_sec m => exts (\lam j => tupleBeta {P1})
           }
      \in transport (IsEquiv __) (ext \lam h => exts \lam j => inv o-assoc *> pmap (`∘ h) (tupleBeta {P1})) $ IsEquiv.trans ((p x g c).isEqualizer z) e
  \where {
    \open vsheafOnSiteWithBasis

    \func product1 (x : C) {J : \Set} (g : J -> ObOver x)
      => D.product (\lam j => F (g j).1)

    \func product2 (x : C) {J : \Set} (g : J -> ObOver x)
      => D.product (\lam (j : \Sigma J J) => F (pullback (g j.1).2 (g j.2).2))

    \func leftMap (x : C) {J : \Set} (g : J -> ObOver x)
      => (product2 x g).tupleMap (\lam j => F.Func pbProj1 ∘ (product1 x g).proj j.1)

    \func rightMap (x : C) {J : \Set} (g : J -> ObOver x)
      => (product2 x g).tupleMap (\lam j => F.Func pbProj2 ∘ (product1 x g).proj j.2)

    \func eqMap (x : C) {J : \Set} (g : J -> ObOver x)
      => (product1 x g).tupleMap (\lam j => F.Func (g j).2)
  }

\class SheafOnSubsite \noclassifying {C' : Precat} {C : Site} (i : Functor C' C) {D : CompleteCat} (F : VSheaf D (inducedSite i)) {
  \instance doubleLimit {x : C} (s : Sieve x) => \new RightKanExt.DoubleLimit {_} {_} {_} {D} i.op F s.diagram.op

  \func FExt : Functor C.op D
    => RightKanExt D i.op F

  \lemma extend : VSheaf D C FExt \cowith
    | isSheaf {x} {s : Sieve x} x<s => run {
        iso_lim (Cone.map FExt s.cone) (D.limit (Comp FExt s.diagram.op)),
        -- First, we use a lemma about Kan extensions to rewrite the double limit in the codomain as a single limit.
        RightKanExt.DoubleLimit.map_iso s.cone,
        -- Now, we get a map f1 : lim_{f : i t -> x} F(t) -> lim_{f : i t -> w, g : w -> x | s g} F(t) and we need to show it is an iso.
        \let A => RightKanExt.lim {_} {_} {D} {i.op} F x,
        \let B => RightKanExt.DoubleLimit.lim' {doubleLimit s},
        \let f1 : Hom A B => limMap {B} (RightKanExt.DoubleLimit.map_cone s.cone),
        -- By the lemma bellow, we have an iso I1 between the domain of the map and lim_{f : i t -> x, g : y -> t | s (f `o` i g)} F(y).
        \let C => iso.cod s Id,
        \let I1 : Iso {D} {A} {C} => iso s Id,
        -- Now, we can show that f1 factors through I1; so, we get a map f2 such that f2 `o` f1 = I1.
        \let f2 => transFuncMap C B (unfold {?}) {?},
        -- By the lemma bellow, we have an iso I2 between B and lim_{f : y -> t, g : t -> w, h : i w -> x | s (f `o` i (g `o` f))} F(y).
        -- Now, we can show that f2 factors through I2.
        -- By 2-out-of-6, f1 is an iso.
        {?}
      }

  \func comma (x : C) => commaPrecat.rightForget (Const {TrivialCat} {C.op} x) i.op

  \lemma iso {x : C} (s : Sieve x) {J : Precat} (G : Functor J (commaPrecat (Const {TrivialCat} {C.op} x) i.op))
    : Iso (transFuncMap
            (cod s G)
            (D.limit (Comp F (Comp (commaPrecat.rightForget (Const {TrivialCat} {C.op} x) i.op) G)))
            (Comp (commaPrecat.leftForget (Comp (comma x) G) Id) (subPrecat.pred.embedding _))
            (unfold \new NatTrans {
              | trans w => Func {F} w.1.3
              | natural {y} {z} f => unfold $ inv Func-o *> pmap (Func {F}) f.3 *> Func-o
            }))
    => {?}
    \where
      \func cod {x : C} (s : Sieve x) {J : Precat} (G : Functor J (commaPrecat (Const {TrivialCat} {C.op} x) i.op))
        => D.limit (Comp F (Comp (commaPrecat.rightForget (Comp (comma x) G) Id) (subPrecat.pred.embedding $ later (\lam (j,y,f) => s {i y} ((G j).3 ∘ i.Func f)))))
} \where {
  \open Limit
}
-}