\import Algebra.Meta
\import Category
\import Category.Functor
\import Category.Limit
\import Category.Slice
\import Category.Subcat
\import Category.Topos.Presheaf
\import Category.Topos.Sheaf.Site
\import Category.Topos.Sheaf.SiteHom
\import Equiv
\import Function (IsInj, IsSurj)
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Lattice.CompleteLattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set.SetCategory
\import Set.Subset
\import Topology.Locale
\import Topology.Locale.LocaleCat
\import Topology.Locale.PreorderSite
\open CompleteLattice

\record MatchingFamily.{s,o1,h1,o2,h2} {C : Precat.{o1,h1}} {D : Precat.{o2,h2}} (F : Functor C.op D) {J : \Type s} (x : C) (P : J -> ObOver x) (d : D)
  | \coerce family (j : J) : Hom d (F (P j).1)
  | isMatching {j j' : J} {z : C} {g : Hom z (P j).1} {g' : Hom z (P j').1} : (P j).2 ∘ g = (P j').2 ∘ g' -> F.Func g ∘ family j = F.Func g' ∘ family j'
  \where {
    \func matchingFamily.{s,o1,h1,o2,h2} {C : Precat.{o1,h1}} {D : Precat.{o2,h2}} (F : Functor C.op D) {J : \Type s} (x : C) (P : J -> ObOver x) (d : D) (h : Hom d (F x)) : MatchingFamily F x P d \cowith
      | family j => Func (P j).2 ∘ h
      | isMatching gg' => inv o-assoc *> pmap (`∘ h) (inv Func-o *> pmap Func (later gg') *> Func-o) *> o-assoc

    \lemma inj-char.{s,o1,h1,o2,h2} {C : Precat.{o1,h1}} {D : Precat.{o2,h2}} {F : Functor C.op D} {J : \Type s} {x : C} {P : J -> ObOver x} {d : D}
      : IsInj (matchingFamily F x P d) <-> ∀ {h h' : Hom d (F x)} (\Pi (j : J) -> F.Func (P j).2 ∘ h = F.Func (P j).2 ∘ h') (h = h')
      => (\lam Fs hh' => Fs (exts hh'), \lam Fs hh' => Fs \lam j => pmap {MatchingFamily F x P d} (__ j) hh')

    \func map.{s,o1,h1,o2,h2} {C : Precat.{o1,h1}} {D : Precat.{o2,h2}} (F : Functor C.op D) {I J : \Type s} (f : I -> J) {x : C} (P : J -> ObOver x) (d : D) (mf : MatchingFamily F x P d) : MatchingFamily F x (\lam i => P (f i)) d \cowith
      | family i => mf (f i)
      | isMatching => isMatching
      \where {
        \lemma isEquiv (fs : IsSurj f) : IsEquiv (map F f P d)
          => IsEquiv.fromInjSurj (\lam p => exts \lam j => \case \elim j, fs j \with {
            | _, inP (i,idp) => path (p __ i)
          }) \lam mf =>
            \let t j => TruncP.rec-set {_} {Hom d (F (P j).1) } (fs j) (\lam s => Func (C.idtoiso $ pmap (\lam x => (P x).1) $ inv s.2).f ∘ mf s.1)
              \lam s s' => mf.isMatching $ inv (ObOver.unequals (pmap P (inv s.2))) *> ObOver.unequals (pmap P (inv s'.2))
            \in inP (\new MatchingFamily {
              | family j => (t j).1
              | isMatching {j} {j'} gg' => \case (t j).2, (t j').2 \with {
                | inP (s,sp), inP (s',s'p) =>
                  \have aux => mf.isMatching $ inv o-assoc *> pmap (`∘ _) (inv $ ObOver.unequals (pmap P (inv s.2))) *> gg' *> pmap (`∘ _) (ObOver.unequals (pmap P (inv s'.2))) *> o-assoc
                  \in pmap (_ ∘) (inv sp) *> inv o-assoc *> pmap (`∘ _) (inv Func-o) *> aux *> pmap (`∘ _) Func-o *> o-assoc *> pmap (_ ∘) s'p
              }
            }, exts \lam i => TruncP.rec-set-eval (later (i,idp)) *> pmap (`∘ _) (later Func-id) *> id-left)
      }
  }

\func PresieveMatchingFamily.{o1,h1,o2,h2} {C : Precat.{o1,h1}} {D : Precat.{o2,h2}} (F : Functor C.op D) (x : C) (P : Presieve x) (d : D)
  => MatchingFamily F {Given P} x __.1 d
  \where {
    \func matchingFamily.{o1,h1,o2,h2} {C : Precat.{o1,h1}} {D : Precat.{o2,h2}} (F : Functor C.op D) (x : C) (P : Presieve x) (d : D) (h : Hom d (F x)) : PresieveMatchingFamily F x P d
      => MatchingFamily.matchingFamily F {Given P} x __.1 d h
  }

\func IsSeparatedPresheaf.{o2,h2,o1,h1} {C : Site.{o1,h1}} {D : Precat.{o2,h2}} (F : Functor C.op D)
  => ∀ {x : C} ∀ {S : isCover x} {d : F.D} (IsInj {_} {PresieveMatchingFamily F x S d} (PresieveMatchingFamily.matchingFamily F x S d))
  \where {
    \protected \lemma char : IsSeparatedPresheaf F <-> ∀ {x : C} ∀ {S : isCover x} {d : F.D} {h h' : Hom d (F x)} (∀ {y : S} (F.Func y.2 ∘ h = F.Func y.2 ∘ h') -> h = h')
      => (\lam Fs Sc hh' => Fs Sc $ exts \lam j => hh' j.2,
          \lam Fs {x} {S} Sc {d} hh' => Fs Sc \lam {y} Sy => pmap {PresieveMatchingFamily F x S d} (family {__} (y,Sy)) hh')
  }

\class SeparatedVPresheaf.{s,o,h} \extends VPresheaf.{o,h,s,s} {
  \override C : Site.{s,s}
  | isSeparated : IsSeparatedPresheaf F

  \lemma separated-covering-inj {x : C} {U : Presieve x} (x<=U : Covering x U) {d : D} : IsInj (PresieveMatchingFamily.matchingFamily F x U d) \elim x<=U
    | covering-inj s p ps=id Up => MatchingFamily.inj-char.2 $ later \lam c => inv id-left *> pmap (`∘ _) (inv Func-id *> pmap F.Func (inv ps=id) *> Func-o) *> o-assoc *> pmap (Func s ∘) (c (_,Up)) *> inv o-assoc *> pmap (`∘ _) (inv Func-o *> pmap F.Func ps=id *> Func-id) *> id-left
    | covering-trans x<=T T<=U => MatchingFamily.inj-char.2 $ later \lam c => MatchingFamily.inj-char.1 (isSeparated x<=T) \lam t =>
      MatchingFamily.inj-char.1 (separated-covering-inj (T<=U t.2)) \lam (z, inP (u,Uu,z>u,z>u_t)) =>
        inv o-assoc *> pmap (`∘ _) (inv Func-o *> pmap F.Func (inv z>u_t) *> Func-o) *> o-assoc *> pmap (Func z>u ∘) (c (u,Uu)) *> inv o-assoc *> pmap (`∘ _) (inv Func-o *> pmap F.Func z>u_t *> Func-o) *> o-assoc

  \lemma separated-covering {x : C} {U : Presieve x} (x<=U : Covering x U) {d : D} {g g' : Hom d (F x)} (p : ∀ {u : U} (F.Func u.2 ∘ g = F.Func u.2 ∘ g')) : g = g'
    => separated-covering-inj x<=U $ exts \lam j => p j.2

  \lemma covering-comp {x : C} {d : D} {I : \Type s} {P : I -> ObOver x} (Pe : IsEquiv (MatchingFamily.matchingFamily F x P d))
                       {J : I -> \Type s} {Q : \Pi {i : I} -> J i -> ObOver (P i).1} (Qc : \Pi {i : I} -> Covering (P i).1 (TSetIm Q))
                       (Qe : \Pi {i : I} -> IsEquiv (MatchingFamily.matchingFamily F (P i).1 Q d))
    : IsEquiv (MatchingFamily.matchingFamily F {\Sigma (i : I) (J i)} x (\lam s => ((Q s.2).1, (P s.1).2 ∘ (Q s.2).2)) d)
    => inP \new QEquiv {
      | ret (mf : MatchingFamily F x _ d) => IsEquiv.ret Pe
        \let smf i => \new MatchingFamily F _ Q d {
          | family j => mf.family (i,j)
          | isMatching gg' => mf.isMatching (o-assoc *> pmap (_ ∘) gg' *> inv o-assoc)
        }
        \in \new MatchingFamily {
          | family i => IsEquiv.ret Qe (smf i)
          | isMatching {i} {i'} {z} {g} {g'} gg' => separated-covering (Covering.covering-stable g Qc) \lam {a} => \case \elim __ \with {
            | inP (_, inP (j,idp), a>qj, a>qj_g) => inv o-assoc *> pmap (`∘ _) (inv (pmap F.Func a>qj_g *> Func-o) *> Func-o) *> o-assoc *>
              pmap {MatchingFamily F _ Q d} (_ ∘ family {__} j) (IsEquiv.f_ret Qe) *> separated-covering (Covering.covering-stable (g' ∘ a.2) Qc) \lam {b} => \case \elim __ \with {
                | inP (_ ,inP (j',idp), d>qj', d>qj'_g'a) => inv o-assoc *> pmap (`∘ _) (inv Func-o) *> later (mf.isMatching $ inv o-assoc *> pmap (`∘ _) (o-assoc *> pmap (_ ∘) a>qj_g *> inv o-assoc *> pmap (`∘ _) gg' *> o-assoc) *> o-assoc *> pmap (_ ∘) (inv d>qj'_g'a) *> inv o-assoc) *> inv (pmap {MatchingFamily F _ Q d} (_ ∘ family {__} j') (IsEquiv.f_ret Qe)) *> inv o-assoc *> pmap (`∘ _) (inv Func-o *> pmap F.Func (d>qj'_g'a *> o-assoc) *> Func-o) *> o-assoc *> pmap (`∘ _) Func-o *> o-assoc
              }
          }
        }
      | ret_f h => pmap (IsEquiv.ret Pe) (exts \lam i => pmap (IsEquiv.ret Qe) (exts \lam j => pmap (`∘ h) Func-o *> o-assoc) *> IsEquiv.ret_f Qe) *> IsEquiv.ret_f Pe
      | f_sec mf => exts \lam s => pmap (`∘ _) Func-o *> o-assoc *> pmap {MatchingFamily F x P d} (_ ∘ family {__} s.1) (IsEquiv.f_ret Pe) *> pmap {MatchingFamily F _ Q d} (family {__} s.2) (IsEquiv.f_ret Qe)
    }

  \lemma covering-refined {x : C} {I : \Type s} {P : I -> ObOver x} (Pc : Covering x (TSetIm P))
    {J : \Type s} {Q : J -> ObOver x} (P<=Q : ∀ (i : I) ∃ (j : J) (f : Hom (P i).1 (Q j).1) ((Q j).2 ∘ f = (P i).2))
    {d : D} (e : IsEquiv (MatchingFamily.matchingFamily F x P d)) : IsEquiv (MatchingFamily.matchingFamily F x Q d)
    => split {_} {x} {\Sigma (i : I) (j : J) (f : Hom (P i).1 (Q j).1) ((Q j).2 ∘ f = (P i).2)}
      (Covering.covering-sub Pc \lam t => TSetIm-elim (\lam i => \case P<=Q i \with {
        | inP (j,f,p) => TSetIm-con $ later (i,j,f,p)
      }) t)
      (\lam s => (s.2,s.3,s.4))
      (IsEquiv.trans e $ MatchingFamily.map.isEquiv \lam i => \case P<=Q i \with {
        | inP (j,f,p) => inP $ later ((i,j,f,p),idp)
      })
    \where
      \private \lemma split {x : C} {I : \Type s} {P : I -> ObOver x} (Pc : Covering x (TSetIm P))
        {J : \Type s} {Q : J -> ObOver x} (P<=Q : ∀ (i : I) Given (j : J) (f : Hom (P i).1 (Q j).1) ((Q j).2 ∘ f = (P i).2))
        {d : D} (e : IsEquiv (MatchingFamily.matchingFamily F x P d)) : IsEquiv (MatchingFamily.matchingFamily F x Q d)
        => \let map (mf : MatchingFamily F x Q d) : MatchingFamily F x P d => \new MatchingFamily {
                  | family i => Func (P<=Q i).2 ∘ mf (P<=Q i).1
                  | isMatching {i} {i'} gg' => inv o-assoc *> pmap (`∘ _) (inv Func-o) *> mf.isMatching (inv o-assoc *> pmap (`∘ _) (P<=Q i).3 *> gg' *> pmap (`∘ _) (inv (P<=Q i').3) *> o-assoc) *> pmap (`∘ _) Func-o *> o-assoc
                }
           \in inP \new QEquiv {
             | ret mf => IsEquiv.ret e (map mf)
             | ret_f h => pmap (IsEquiv.ret e) (exts \lam i => inv o-assoc *>  pmap (`∘ h) (inv Func-o *> pmap F.Func (P<=Q i).3)) *> IsEquiv.ret_f e
             | f_sec mf => exts \lam j => separated-covering (Covering.covering-stable (Q j).2 Pc) \case \elim __ \with {
               | inP (_, inP (i,idp), f, f_Q) => inv o-assoc *> pmap (`∘ _) (inv (pmap F.Func f_Q *> Func-o) *> Func-o) *>
                 o-assoc *> pmap (_ ∘) (pmap {MatchingFamily F x P d} (family {__} i) (IsEquiv.f_ret e {map mf})) *> inv o-assoc *> pmap (`∘ _) (inv Func-o) *> mf.isMatching (inv o-assoc *> pmap (`∘ f) (P<=Q i).3 *> f_Q)
             }
           }
}

\func IsSheaf.{o2,h2,o1,h1} {C : Site.{o1,h1}} {D : Precat.{o2,h2}} (F : Functor C.op D)
  => ∀ {x : C} ∀ {S : isCover x} (SheafCond F S)
  \where {
    \func SheafCond (F : Functor C.op D) {x : C} (S : Presieve x) : \Prop
      => \Pi {d : D} -> IsEquiv {_} {PresieveMatchingFamily F x S d} (PresieveMatchingFamily.matchingFamily F x S d)

    \lemma sheaf-lim {x : C} {S : Presieve x} : SheafCond F S <-> IsLimitCone cone
      => \let e d => \new QEquiv {PresieveMatchingFamily F x S d} {Cone coneF d} {
        | f mf => \new Cone {
          | coneMap j => Func j.4 ∘ mf (j.2,j.3)
          | coneCoh h => $ inv o-assoc *> pmap (`∘ _) (inv Func-o) *> mf.isMatching (inv o-assoc *> h.2)
        }
        | ret c => \new MatchingFamily {
          | family j => c.coneMap (j.1.1, j.1, j.2, id j.1.1)
          | isMatching {j} {j'} {z} {g} {g'} p => c.coneCoh {j.1.1, j.1, j.2, id j.1.1} (g, pmap (`∘ g) id-right) *> inv id-left *> pmap (`∘ _) (inv Func-id) *> c.coneCoh {z, j.1, j.2, g} {z, j'.1, j'.2, g'} (id z, id-right *> p) *> inv (c.coneCoh {j'.1.1, j'.1, j'.2, id j'.1.1} (g', pmap (`∘ g') id-right))
        }
        | ret_f mf => exts \lam j => pmap (`∘ _) Func-id *> id-left
        | f_sec c => exts \lam j => c.coneCoh {j.2.1, j.2, j.3, id j.2.1} (j.4, pmap (`∘ _) id-right)
      } \in (\lam sc d => transport IsEquiv (ext \lam h => exts \lam j => inv $ pmap (`∘ h) Func-o *> o-assoc) $ IsEquiv.trans sc $ inP (e d),
             \lam lc {d} => transport IsEquiv (ext \lam h => exts \lam j => pmap (Func __ ∘ h) id-right) $ IsEquiv.trans (lc d) $ inP $ symQEquiv (e d))
      \where {
        \func coneJ : Precat \cowith
          | Ob => Given (y : C) (px : S) (Hom y px.1)
          | Hom t s => \Sigma (f : Hom s.1 t.1) (t.2.2 ∘ t.4 ∘ f = s.2.2 ∘ s.4)
          | id s => (id s.1, id-right)
          | o f g => (g.1 ∘ f.1, inv o-assoc *> pmap (`∘ _) g.2 *> f.2)
          | id-left => ext id-right
          | id-right => ext id-left
          | o-assoc => ext (inv o-assoc)

        \func coneF : Functor coneJ D \cowith
          | F s => F s.1
          | Func f => Func f.1
          | Func-id => Func-id
          | Func-o => Func-o

        \func cone : Cone coneF (F x) \cowith
          | coneMap j => Func (j.2.2 ∘ j.4)
          | coneCoh h => inv Func-o *> pmap F.Func h.2
      }
  }

-- | Sheaves valued in {D}
\class VSheaf.{s,o,h} \extends SeparatedVPresheaf.{s,o,h} {
  | isSheaf : IsSheaf F
  | isSeparated => \lam Sc {d} => IsEquiv.isInj (isSheaf Sc)

  \lemma sheaf-covering {x : C} {U : Presieve x} (x<=U : Covering x U) {d : D} : IsEquiv (PresieveMatchingFamily.matchingFamily F x U d) \elim x<=U
    | covering-inj s p ps=id Up \as x<=U => IsEquiv.fromInjSurj (separated-covering-inj x<=U) \lam mf => inP (Func s ∘ mf.family (_, Up), exts \lam j =>
      inv o-assoc *> pmap (`∘ _) (inv Func-o) *> mf.isMatching (inv o-assoc *> pmap (`∘ _) ps=id *> id-left *> inv id-right) *> pmap (`∘ _) Func-id *> id-left)
    | covering-trans {T} x<=T T<=U => covering-refined
      (Covering.covering-trans x<=T \lam {t} Tt => Covering.covering-sub (T<=U Tt) \lam {z} r => inP $ later (_, TSetIm-con $ later ((t,Tt),(z,r)), id z.1, id-right))
      (later \lam ((t,Tt), (z, inP (u,Uu,f,f_t))) => inP ((u,Uu),f,f_t)) $
      covering-comp {_} {x} {d} {Given T} {__.1} (isSheaf x<=T) {\lam t => Given (z : ObOver t.1.1) ∃ (u : U) (f : Hom z.1 u.1) (u.2 ∘ f = t.1.2 ∘ z.2)} {__.1}
        (\lam {t} => Covering.covering-sub (T<=U t.2) \lam {z} r => TSetIm-con $ later (z,r))
        (\lam {t} => sheaf-covering (T<=U t.2))

  \lemma sheaf-matchingFamily {J : \Type s} {x : C} {P : J -> ObOver x} (x<=U : Covering x (TSetIm P)) {d : D} : IsEquiv (MatchingFamily.matchingFamily F x P d)
    => IsEquiv.trans (sheaf-covering x<=U) $ MatchingFamily.map.isEquiv {C} {D} {F} {J} {\Sigma (px : ObOver x) (TSetIm P px)} {\lam j => (P j, inP (j,idp))} \lam (_, inP (j,idp)) => inP (j,idp)

  \lemma direct_image.{s'} {C' : Site.{s',s'}} (f : SiteHom C' C) : VSheaf D C' (Comp F f.op) \cowith
    | isSheaf {x} {S} xS {d} => IsEquiv.trans (isSheaf (f.Func-cover xS)) $
        IsEquiv.trans (MatchingFamily.map.isEquiv {C} {D} {F} {Given S} {Given (py : ObOver (f x)) ∃ (px : S) (py = (f px.1, Func px.2))} {\lam s => (_, inP (s.1,s.2,idp))} \lam (_, inP (px,Spx,idp)) => inP ((px,Spx),idp)) $
        inP \new QEquiv {
          | f mf => \new MatchingFamily {
            | family => mf.family
            | isMatching {j} {j'} gg' => mf.isMatching $ inv Func-o *> pmap Func gg' *> Func-o
          }
          | ret mf => \new MatchingFamily {
            | family => mf.family
            | isMatching {j} {j'} {z} {g} {g'} gg' => separated-covering (f.Func-flat-pullback gg') \lam {u} (inP (w,w>j,w>j',c,h,hl,hr)) =>
              inv o-assoc *> pmap (`∘ _) (inv Func-o) *> pmap (`∘ _) (pmap F.Func (inv hl) *> Func-o) *> o-assoc *> pmap (_ ∘) (mf.isMatching c) *> inv o-assoc *> pmap (`∘ _) (inv Func-o *> pmap F.Func hr) *> pmap (`∘ _) Func-o *> o-assoc
          }
          | ret_f => idpe
          | f_sec => idpe
        }
} \where {
  \func restrict.{s,o,h} {L : Locale.{s}} (a : L) (F : VSheaf.{s,o,h} { | C => L }) : VSheaf F.D (L.restrict a) \cowith
    | F => Comp F Locale.restrict.functor.op
    | isSheaf {x} {S} x<=S {d} => IsEquiv.trans (F.isSheaf {x.1} {\lam px => S ((px.1, px.2 <=∘ x.2), px.2)} (x<=S <=∘ SJoin-univ \lam {b} s => Join-cond $ later (s.1, transport S (ext $ ext idp) s.2))) $ inP \new QEquiv {
      | f mf => \new MatchingFamily {
        | family j => mf ((j.1.1.1, j.1.2), \box transport S (ext $ ext idp) j.2)
        | isMatching {j} {j'} _ => mf.isMatching {(j.1.1.1, j.1.2), _} {(j'.1.1.1, j'.1.2), _} prop-pi
      }
      | ret mf => \new MatchingFamily {
        | family j => mf (((j.1.1, j.1.2 <=∘ x.2), j.1.2), j.2)
        | isMatching {j} {j'} {z} {g} {g'} _ => mf.isMatching {_, j.2} {_, j'.2} {z, g <=∘ j.1.2 <=∘ x.2} prop-pi
      }
      | ret_f => idpe
      | f_sec mf => exts \lam j => cong $ ext $ ext (ext idp)
    }

  \lemma direct_image_locale.{s,o,h} {L L' : Locale.{s}} (f : FrameHom L' L) (S : VSheaf.{s,o,h} { | C => L }) : VSheaf S.D L' (Comp S f.functor.op)
    => S.direct_image f.functor
}

\instance VSheafCat.{s,v} (D : Cat.{\suc v, v}) (C : Site.{s,s}) : Cat
  => subCat {VPresheafCat D C} {VSheaf D C} (\new Embedding {
    | f P => P
    | isEmb _ _ => \new Retraction {
      | sec p => ext VSheaf { | VPresheaf => p }
      | f_sec => idpe
    }
  })
  \where {
    \lemma functor-iso {F G : VSheaf D C} (e : Iso {FunctorCat C.op D} {F} {G}) : Iso {VSheafCat D C} {F} {G} e e.hinv \cowith
      | hinv_f => e.hinv_f
      | f_hinv => e.f_hinv
  }

-- | Sheaves valued in sets
\class Sheaf.{s,v} \extends VSheaf.{s, \suc v, v}
  | D => SetCat.{v}

\func IsPreorderSheaf.{o,h,s} {C : PreorderSite.{s}} {D : Precat.{o,h}} (F : Functor C.op D)
  => ∀ {x : C} ∀ {S : isBasicCover x} (∀ {y : S} (y <= x)) {d : F.D}
      (IsEquiv {_} {PresieveMatchingFamily F x _ d} (PresieveMatchingFamily.matchingFamily F x (\lam px => S px.1) d))
  \where {
    \lemma toSheaf (FS : IsPreorderSheaf F) : IsSheaf F
      => \lam {x} {S} x<=S {d} => IsEquiv.trans (FS x<=S \lam s => s.1) $ inP \new QEquiv {
        | f mf => \new MatchingFamily {
          | family j => mf (j.1, (j.1.2, j.2))
          | isMatching {j} {j'} => mf.isMatching {j.1, (j.1.2, j.2)} {j'.1, (j'.1.2, j'.2)}
        }
        | ret mf => \new MatchingFamily {
          | family j => mf (j.1, transport S (ext idp) j.2.2)
          | isMatching {j} {j'} => mf.isMatching {j.1, transport S (ext idp) j.2.2} {j'.1, transport S (ext idp) j'.2.2}
        }
        | ret_f mf => exts \lam j => cong (ext idp)
        | f_sec mf => exts \lam j => cong (ext idp)
      }

    \lemma makeSheaf (FS : IsPreorderSheaf F) : VSheaf D C F \cowith
      | isSheaf {x} => toSheaf FS {x}

    \lemma fromSheaf.{o,h,s} {C : PreorderSite.{s}} {D : Precat.{o,h}} {F : Functor C.op D} (FS : IsSheaf F) : IsPreorderSheaf F
      => \lam {x} {S} x<=S S<=x => FS {x} {\lam px => S px.1} $ transport (isBasicCover x) (ext \lam y => propExt (\lam Sy => (S<=x Sy, Sy)) __.2) x<=S
  }

\lemma SiteLocaleSheaf.{s,o,h} {P : PreorderSite.{s}} {D : CompleteCat.{s,o,h}} (F : Functor P.op D) (FS : IsPreorderSheaf F) : VSheaf D (SiteLocale P) extend \cowith
  | isSheaf {U} {S} U<=S {d} =>
    \let | cover {a} (Ua : U.1 a) : Covering a (\lam b => ∃ (V : Opens P) (V<=U : V <= U) (S (V,V<=U)) (V.1 b.1))
            => Cover.Cover_Covering $ Cover.cover-sub (Cover.cover-down (U<=S Ua)) \lam {y} (inP (z, inP (V, (V<=U, SV), Vz), y<=z, y<=a)) => (y<=a, inP (V, V<=U, SV, V.2 $ cover-inj y<=z Vz))
         | lim {U} => extend.lim U
    \in IsEquiv.fromInjSurj (\lam {h} {h'} p => limUnique \lam j => (IsPreorderSheaf.makeSheaf FS).separated-covering (cover j.2) \lam {y} (inP (V,V<=U,SV,Vy)) =>
        \have | q => lim.coneCoh {j} {y.1, V<=U Vy} y.2
              | r => lim.limBeta (extend.cone V<=U) (y.1,Vy)
        \in inv o-assoc *> pmap (`∘ h) q *> pmap (`∘ h) (inv r) *> o-assoc *> path (\lam i => lim.coneMap (y.1,Vy) ∘ p i (_,SV)) *> inv o-assoc *> pmap (`∘ h') r *> pmap (`∘ h') (inv q) *> o-assoc)
      \lam mf =>
        \have | mf' {a} (Ua : U.1 a) : MatchingFamily F {\Sigma (pa : ObOver a) (V : Opens P) (V<=U : V <= U) (S (V,V<=U)) (V.1 pa.1)} a __.1 d (\lam s => lim.coneMap (s.1.1, s.5) ∘ mf (_, s.4)) => \new MatchingFamily {
                | isMatching {j} {j'} {z} {g} {g'} _ =>
                  \have t => pmap ((lim {embed z}).coneMap (z, Cover.cover-refl idp) ∘) $ mf.isMatching {_,j.4} {_,j'.4} {embed z} {embed-univ $ j.2.2 $ cover-inj g j.5} {embed-univ $ j'.2.2 $ cover-inj g' j'.5} prop-pi
                  \in inv o-assoc *> pmap (`∘ _) (lim.coneCoh {j.1.1, j.5} g) *> pmap (`∘ _) (inv $ (lim {embed z}).limBeta (extend.cone (embed-univ _)) _) *> o-assoc *> t *> inv o-assoc *> pmap (`∘ _) ((lim {embed z}).limBeta (extend.cone (embed-univ _)) _) *> pmap (`∘ _) (inv $ lim.coneCoh {j'.1.1, j'.5} g') *> o-assoc
              }
              | e {a} (Ua : U.1 a) => IsEquiv.splitSurj ((IsPreorderSheaf.makeSheaf FS).sheaf-matchingFamily (Covering.covering-sub (cover Ua) \lam {b} (inP (V,V<=U,SV,Vb)) => TSetIm-con $ later (b,V,V<=U,SV,Vb))) (mf' Ua)
        \in inP (lim.limMap \new Cone {
          | coneMap a => (e a.2).1
          | coneCoh {j} {j'} j'<=j => (IsPreorderSheaf.makeSheaf FS).separated-covering (cover j'.2) \lam {y} (inP (V,V<=U,SV,Vy)) => inv o-assoc *> pmap (`∘ _) (inv Func-o) *> path (\lam i => (e j.2).2 i ((y.1, y.2 <=∘ j'<=j), V, V<=U, SV, Vy)) *> inv (path \lam i => (e j'.2).2 i (y, V, V<=U, SV, Vy))
        }, exts \lam (V,SV) => limUnique \lam (y,Vy) => inv o-assoc *> pmap (`∘ _) (lim.limBeta (extend.cone V.2) (y,Vy)) *> lim.limBeta _ (y, V.2 Vy) *> inv (pmap (`∘ _) Func-id *> id-left) *> path (\lam i => (e (\box V.2 Vy)).2 i (ObOver.id, V.1, V.2, SV, Vy)))
  \where {
    \open SiteLocale

    \func extend : Functor (SiteLocale P).op D \cowith
      | F b => lim b
      | Func {a} {b} b<=a => (lim b).limMap (cone b<=a)
      | Func-id {b} => (lim b).limUniqueBeta \lam j => inv id-right
      | Func-o {a} {b} {c} {b<=c} {a<=b} => (lim c).limUniqueBeta {lim a} \lam j => inv (pmap (`∘ _) ((lim c).limBeta (cone b<=c) j) *> (lim b).limBeta (cone a<=b) (j.1, b<=c j.2)) *> o-assoc
      \where {
        \func limFunctor (b : Opens P)
          => Comp F (subPrecat.embedding \lam (t : Set.Total b.1) => t.1).op

        \func lim (b : Opens P)
          => D.limit (limFunctor b)

        \func cone {a b : Opens P} (b<=a : b <= a) : Cone (limFunctor b) (lim a) \cowith
          | coneMap (x,x<=b) => coneMap (later (x, b<=a x<=b))
          | coneCoh {j} {j'} => \case \elim j, \elim j' \with { | (_,_), (_,_) => \lam h => coneCoh $ later h }
      }
  }

\lemma sheaf-reflect.{s,o,h} {C : Site.{s,s}} {D E : Cat.{o,h}} (G : Functor D E)
                             (G-lim : \Pi {J : Precat.{s,s}} (H : Functor J D) -> ReflectsLimit G H) (F : Functor C.op D) (R : VSheaf E C (Comp G F)) : VSheaf D C F \cowith
  | isSheaf x<=S => IsSheaf.sheaf-lim.2 $ G-lim _ IsSheaf.sheaf-lim.cone $ (IsSheaf.sheaf-lim {C} {E} {R}).1 (R.isSheaf x<=S)

\lemma sheaf-preserve.{s,o,h} {C : Site.{s,s}} {D E : Cat.{o,h}} (G : Functor D E)
                              (G-lim : \Pi {J : Precat.{s,s}} (H : Functor J D) -> PreservesLimit G H) (F : VSheaf D C) : VSheaf E C (Comp G F) \cowith
  | isSheaf x<=S => (IsSheaf.sheaf-lim {C} {E} {Comp G F}).2 $ G-lim IsSheaf.sheaf-lim.coneF IsSheaf.sheaf-lim.cone $ IsSheaf.sheaf-lim.1 (F.isSheaf x<=S)