\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Ring.RingCategory
\import Algebra.Ring.RingHom
\import Category
\import Category.Functor
\import Category.Topos.Sheaf
\import Equiv
\import Equiv.Path
\import Equiv.Sigma
\import Function.Meta
\import Logic
\import Meta
\import Order.Lattice
\import Order.Lattice.CompleteLattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Topology.Locale
\import Topology.Locale.LocaleCat

\record RingedLocale.{s,v} (\coerce L : Locale.{s}) (R : VSheaf CRingCat.{v} L)
  \where {
    \use \coerce fromSheaf.{s,v} {L : Locale.{s}} (S : VSheaf CRingCat.{v} L) => \new RingedLocale L S

    {-
    \func equality (L L' : RingedLocale) : Equiv {L = L'} {\Sigma (p : L.L = L'.L) (VSheaf.direct_image_locale (Iso.f {Precat.idtoiso p}) L.R = L'.R)}
      => pathEquiv _ $ later \lam {L : RingedLocale} {L' : RingedLocale} => \new Retraction {
        | f => fromPath
        | sec s => toPath s.1 s.2
        | f_sec s => {?}
      }
      \where {
        \func fromPath {L L' : RingedLocale} (p : L = L') : \Sigma (p : L.L = L'.L) (VSheaf.direct_image_locale (Iso.f {Precat.idtoiso p}) L.R = L'.R) \elim p
          | idp => (idp, VSheaf.direct_image_id L'.R)

        \func toPath {L L' : RingedLocale} (p : L.L = L'.L) (q : VSheaf.direct_image_locale (Iso.f {Precat.idtoiso p}) L.R = L'.R) : L = L'
          => ext (p, VSheaf.transport_direct_image_locale p L.R *> q)

        \func from-to {LR : RingedLocale} {L' : Locale} {R' : VSheaf CRingCat L'} (p : LR.L = L') (q : VSheaf.direct_image_locale (Iso.f {Precat.idtoiso p}) LR.R = R') : fromPath (toPath {LR} {\new RingedLocale L' R'} p q) = (p,q) \elim p, q
          | idp, idp => unfold toPath {?}
      }
    -}
    \func equality1.{s,v} (L L' : RingedLocale.{s,v}) : QEquiv {L = L'} {\Sigma (p : L.L = L'.L) (transport (VSheaf CRingCat.{v}) p L.R = L'.R)}
      => pathEquiv _ $ later \lam {L L' : RingedLocale.{s,v}} => \new Retraction {
        | f => fromPath.{s,v}
        | sec s => toPath s.1 s.2
        | f_sec s => from-to.{s,v} {L} {L'.L} {L'.R} s.1 s.2
      }
      \where {
        \func fromPath {L L' : RingedLocale} (p : L = L') : \Sigma (p : L.L = L'.L) (transport (VSheaf CRingCat) p L.R = L'.R) \elim p
          | idp => (idp, idp)

        \func toPath {L L' : RingedLocale} (p : L.L = L'.L) (q : transport (VSheaf CRingCat) p L.R = L'.R) : L = L'
          => ext (p, q)

        \func from-to.{s,v} {LR : RingedLocale.{s,v}} {L' : Locale.{s}} {R' : VSheaf CRingCat.{v} L'} (p : LR.L = L') (q : transport (VSheaf CRingCat.{v}) p LR.R = R') : fromPath (toPath {LR} {\new RingedLocale L' R'} p q) = (p,q) \elim p, q
          | idp, idp => idp
      }

    \func equality2 (L L' : RingedLocale) : QEquiv {L = L'} {\Sigma (p : L.L = L'.L) (VSheaf.direct_image_locale (Iso.f {Precat.idtoiso p}) L.R = L'.R)}
      => transQEquiv (equality1 L L') $ sigma-right \lam p => pathConcatEquiv (VSheaf.transport_direct_image p L.R)

    \func equality3 (L L' : RingedLocale) : QEquiv {L = L'} {\Sigma (e : Iso {LocaleCat} {L.L} {L'.L}) (Iso {_} {VSheaf.direct_image_locale e.f L.R} {L'.R})}
      => equality2 L L' `transQEquiv` sigma-left (IsEquiv.toQEquiv univalence) `transQEquiv` sigma-right (later (\lam e => IsEquiv.toQEquiv univalence))
  }

\record RingedLocaleHom.{s,v} (Dom Cod : RingedLocale.{s,v}) (\coerce f : FrameHom Cod Dom) (f# : NatTrans Cod.R (VSheaf.direct_image_locale f Dom.R))
  \where {
    \func fromHomEq {L M : Locale} {f g : FrameHom M L} (p : f = g) (a : M) : f a <= g a
      => transport (\lam (h : FrameHom M L) => f a <= h a) p <=-refl

    \lemma ext.{s,v} {L M : RingedLocale.{s,v}} (f g : RingedLocaleHom L M) (p : f.f = g.f) (q : \Pi (a : M) (x : M.R a) -> L.R.F.Func (fromHomEq p a) (g.f# a x) = f.f# a x) : f = g
      => aux f.f# g.f# p q
      \where {
        \lemma aux.{s,v} {L M : RingedLocale.{s,v}} {f g : FrameHom M L} (f# : NatTrans M.R (VSheaf.direct_image_locale f L.R)) (g# : NatTrans M.R (VSheaf.direct_image_locale g L.R)) (p : f = g) (q : \Pi (a : M) (x : M.R a) -> L.R.F.Func (fromHomEq p a) (g# a x) = f# a x) : (\new RingedLocaleHom L M f f#) = (\new RingedLocaleHom L M g g#) \elim p
          | idp => cong $ exts \lam a => exts (\lam x => inv (q a x) *> pmap (\lam (h : RingHom (L.R (f a)) (L.R (f a))) => h (g# a x)) (L.R.F.Func-id {f a}))
      }
  }

\record LocallyRingedLocale \extends RingedLocale
  | isNonTrivial (a : L) : 0 = {R.F a} 1 -> a <= bottom
  | isLocallyRinged (a : L) (x : R.F a) : a <= Join (\lam b => \Sigma (p : b <= a) (EitherInv \this p x))
  \where {
    \func EitherInv (L : RingedLocale) {a b : L} (p : b <= a) (x : L.R.F a)
      => Monoid.Inv (L.R.F.Func p x) || Monoid.Inv (L.R.F.Func p x + 1)
  }
