\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.Localization
\import Algebra.Monoid.MonoidHom
\import Algebra.Monoid.Sub
\import Algebra.Pointed
\import Algebra.Pointed.PointedHom
\import Algebra.Ring
\import Algebra.Ring.RingCategory
\import Algebra.Ring.RingHom
\import Category
\import Category.Functor
\import Category.Topos.Sheaf
\import Category.Topos.Sheaf.DenseExtend
\import Category.Topos.Sheaf.LocalPredicate
\import Equiv
\import Equiv.Path
\import Equiv.Sigma
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Lattice
\import Order.Lattice.CompleteLattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set.Subset
\import Topology.Locale
\import Topology.Locale.LocaleCat
\import Topology.Locale.PreorderSite
\open SiteLocale
\open Monoid
\open SubMonoid(powers)

\record RingedLocale.{s} (\coerce L : Locale.{s}) (R : VSheaf CRingCat.{s} L) {
  \func GlobalSections : CRing
    => R top
} \where {
  \use \coerce fromSheaf.{s} {L : Locale.{s}} (S : VSheaf CRingCat.{s} L) => \new RingedLocale L S
}

\record RingedLocaleHom.{s} (Dom Cod : RingedLocale.{s}) (\coerce f : FrameHom Cod Dom) (f# : NatTrans Cod.R (VSheaf.direct_image_locale f Dom.R))
  \where {
    \lemma eqSigma {L M : RingedLocale} {g h : RingedLocaleHom L M} (q : g = h) : \Sigma (p : g.f = h.f) (transport (\lam f => NatTrans M.R (VSheaf.direct_image_locale f L.R)) p g.f# = h.f#) \elim q
      | idp => (idp,idp)

    \lemma eqCast {L M : RingedLocale} {f : LocaleHom L M} {g h : RingedLocaleHom L M f} (q : g = {RingedLocaleHom L M} h) : g = h
      => \have s => eqSigma q
         \in Paths.Meta.ext $ rewrite (prop-pi : s.1 = idp) in s.2

    \func castOver {L M : RingedLocale} (h : RingedLocaleHom L M) {f : LocaleHom L M} (p : h.f = f) : \Sigma (h' : RingedLocaleHom h.Dom h.Cod f) (h' = h) \elim p
      | idp => (h,idp)

    \func fromHomEq {L M : Locale} {f g : LocaleHom L M} (p : f = g) (a : M) : f a <= g a
      => transport (\lam (h : LocaleHom L M) => f a <= h a) p <=-refl

    \lemma ext {L M : RingedLocale} (f g : RingedLocaleHom L M) (p : f.f = g.f) (q : \Pi (a : M) (x : M.R a) -> L.R.F.Func (fromHomEq p a) (g.f# a x) = f.f# a x) : f = g
      => aux f.f# g.f# p q
      \where {
        \lemma aux {L M : RingedLocale} {f g : LocaleHom L M} (f# : NatTrans M.R (VSheaf.direct_image_locale f L.R)) (g# : NatTrans M.R (VSheaf.direct_image_locale g L.R)) (p : f = g) (q : \Pi (a : M) (x : M.R a) -> L.R.F.Func (fromHomEq p a) (g# a x) = f# a x) : (\new RingedLocaleHom L M f f#) = (\new RingedLocaleHom L M g g#) \elim p
          | idp => cong $ exts $ \lam a => exts (\lam x => inv (q a x) *> pmap (\lam (h : RingHom (L.R (f a)) (L.R (f a))) => h (g# a x)) (L.R.F.Func-id {f a}))
      }
  }

\record LocallyRingedLocale \extends RingedLocale {
  | isLRLNonTrivial (a : L) : 0 = {R.F a} 1 -> a <= bottom
  | isLocallyRinged (a : L) (x : R.F a) : a <= Join (\lam b => \Sigma (p : b <= a) (Inv (R.F.Func p x) || Inv (R.F.Func p (x + 1))))

  \type IsAffineOpen (c : L) => Given
    (∀ (x : R c) ∃ (b : L) (p : b <= c) (Localization (SubMonoid.powers x) (R b) (R.F.Func p)))
    (∀ {b} (p : b <= c) (b <= Join \lam d => Given (q : d <= b) ∃ (x : R c) (Localization (SubMonoid.powers x) (R d) (R.F.Func (q <=∘ p)))))

  \func IsAffineScheme : \Prop
    => IsAffineOpen top
}

\record LocallyRingedLocaleHom.{s} \extends RingedLocaleHom.{s} {
  \override Dom : LocallyRingedLocale.{s}
  \override Cod : LocallyRingedLocale.{s}

  | isHomLocal {a : Dom} {b : Cod} (a<=fb : a <= f b) {x : Cod.R b} : Inv (Dom.R.F.Func a<=fb (f# b x)) ->
      ∃ (c : Cod) (a <= f c) (c<=b : c <= b) (Inv (Cod.R.F.Func c<=b x))
}

\record LocallyRingedSite.{s} (\coerce P : PreorderSite.{s}) (R : Functor P.op CRingBicat.{s}) (R-sheaf : IsPreorderSheaf R) {
  | isNonTrivialPres (a : P) : 0 = {R a} 1 -> Cover a empty
  | isLocallyRingedPres (a : P) (x : R a) : Cover a (\lam b => \Sigma (p : b <= a) (Inv (R.Func p x) || Inv (R.Func p (x + 1))))

  \func toLocale : LocallyRingedLocale \cowith
    | L => SiteLocale P
    | R => SiteLocaleSheaf {_} {CRingBicat} R R-sheaf
    | isLRLNonTrivial U p {x} Ux => Cover.cover-sub (isNonTrivialPres x $ pmap (__.1 (x,Ux)) p) empty-univ
    | isLocallyRinged U a {x} Ux => Cover.cover-sub (isLocallyRingedPres x (a.1 (x,Ux))) \lam {y} s => inP (embed y, (embed-univ $ U.2 $ cover-inj s.1 Ux, \case s.2 \with {
      | byLeft i => byLeft $ (LimitCRing.inv-char {_} {extend.limFunctor (embed y)}).2 \lam j =>
        (inv-localPredicate {_} {IsPreorderSheaf.makeSheaf R-sheaf}).byCovering (Cover.toCovering j.2) $ later \lam {z} (inP (_,idp,z<=y)) => transport (Inv __) (
          \let Uj : U.1 j.1 => _
          \in inv (path \lam i => R.Func-o i _) *> a.2 {x,Ux} {z.1,_} (later $ z<=y <=∘ s.1) *> inv (a.2 {j.1,Uj} {z.1, U.2 $ cover-inj z.2 Uj} z.2))
        ((R.Func z<=y).func-Inv i)
      | byRight i => byRight $ (LimitCRing.inv-char {_} {extend.limFunctor (embed y)}).2 \lam j =>
        (inv-localPredicate {_} {IsPreorderSheaf.makeSheaf R-sheaf}).byCovering (Cover.toCovering j.2) $ later \lam {z} (inP (_,idp,z<=y)) => transport (Inv __) (unfold $ unfold $
          \let Uj : U.1 j.1 => _
          \in inv (path \lam i => R.Func-o i _) *> func-+ *> pmap2 (+) (a.2 {x,Ux} {z.1,_} (later $ z<=y <=∘ s.1) *> inv (a.2 {j.1,Uj} {z.1, U.2 $ cover-inj z.2 Uj} z.2)) (func-ide *> inv func-ide) *> inv func-+)
        ((R.Func z<=y).func-Inv i)
    }), Cover.cover-refl idp)

  \lemma affineOpen {a : P}
    (ap : ∀ (x : R a) ∃ (b : P) (p : b <= a) (Localization (SubMonoid.powers x) (R b) (R.Func p)))
    (aq : ∀ {b} (p : b <= a) (Cover b \lam d => Given (q : d <= b) ∃ (x : R a) (Localization (SubMonoid.powers x) (R d) (R.Func (q <=∘ p)))))
    : toLocale.IsAffineOpen (embed a)
    => \let | proj c => embedProj {_} {CRingBicat} c
            | proj-eq c => CRingCat.Iso<->IsEquiv.1 (embed-iso R-sheaf {c})
       \in (\lam x => \case ap (proj a x) \with {
              | inP (b,b<=a,bl) => inP (embed b, embed-univ $ cover-inj b<=a idp, Localization.equiv-transport1.reverse (proj a) (proj-eq a) bl (proj b) (proj-eq b) \lam x => later $ path \lam i => embed-natural {_} {CRingBicat} b<=a i x)
            }, \lam {U} U<=a => element_SJoin_<= U<=a <=∘ CompleteLattice.SJoin-univ (later \lam {y} (Uy,y<=a) => embed-univ $
                Cover.cover-sub (aq y<=a) \lam {z} (z<=y, inP (x,zl)) => inP (embed z, (embed-univ $ U.2 $ cover-inj z<=y Uy,
                  inP (IsEquiv.ret (proj-eq a) x, Localization.equiv-transport1.reverse (proj a) (proj-eq a)
                    (transportInv (\lam r => Localization (powers r) _ _) (IsEquiv.f_ret (proj-eq a)) zl) (proj z) (proj-eq z)
                    \lam x => later $ path \lam i => embed-natural {_} {CRingBicat} _ i x)), Cover.cover-refl idp))
       )
} \where \open SiteLocaleSheaf