\import Algebra.Group
\import Algebra.Group.GroupHom
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.Localization
\import Algebra.Monoid.MonoidHom
\import Algebra.Monoid.Sub
\import Algebra.Pointed
\import Algebra.Pointed.PointedHom
\import Algebra.Ring
\import Algebra.Ring.RingCategory
\import Algebra.Ring.RingHom
\import Category
\import Category.Functor
\import Category.Topos.Sheaf
\import Category.Topos.Sheaf.DenseExtend
\import Category.Topos.Sheaf.Site
\import Equiv
\import Equiv.Path
\import Equiv.Sigma
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Lattice
\import Order.Lattice.CompleteLattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set.Subset
\import Topology.Locale
\import Topology.Locale.LocaleCat
\import Topology.Locale.PreorderSite
\open SiteLocale
\open Monoid
\open SubMonoid(powers)

\record RingedLocale.{s} (\coerce L : Locale.{s}) (R : VSheaf CRingCat.{s} L) {
  \func GlobalSections : CRing
    => R top

  \lemma R-equals {a : L} {U : Set L} (a<=U : a <= Join U) {x y : R a} (p : ∀ {b} {c : U} (ba : b <= a) (b <= c) (R.F.Func ba x = R.F.Func ba y)) : x = y
    => path \lam i => (IsSheaf.makeSheaf (sheaf-preserve CRingCat.forget CRingCat.forget.preservesLimit R)).separated-covering {a} {\lam b => ∃ (c : U) (b.1 <= c)}
        (Covering.covering-basic $ meet-univ <=-refl a<=U <=∘ Join-ldistr>= <=∘ L.SJoin-univ \lam {c} Uc => Join-cond $ later (meet-left, inP (c, Uc, meet-right)))
        (\lam {b} (inP (c,Uc,b<=c)) => ext \lam _ => p Uc b.2 b<=c) i ()

  \lemma Inv-restrict {a b : L} (b<=a : b <= a) {x : GlobalSections} (xi : Inv (R.F.Func (top-univ {_} {a}) x)) : Inv (R.F.Func (top-univ {_} {b}) x)
    => transport Inv (inv (path \lam i => R.F.Func-o i x) *> pmap (R.F.Func __ x) prop-pi) $ (R.F.Func b<=a).func-Inv xi
} \where {
  \use \coerce fromSheaf.{s} {L : Locale.{s}} (S : VSheaf CRingCat.{s} L) => \new RingedLocale L S
}

\record RingedLocaleHom.{s} (Dom Cod : RingedLocale.{s}) (\coerce f* : FrameHom Cod Dom) (f# : NatTrans Cod.R (VSheaf.direct_image_locale f* Dom.R)) {
  \func IsIso : \Prop
    => Given (IsEquiv f*) ∀ (b : Cod) (IsEquiv (f# b))
}
  \where {
    \lemma eqSigma {L M : RingedLocale} {g h : RingedLocaleHom L M} (q : g = h) : \Sigma (p : g.f* = h.f*) (transport (\lam f => NatTrans M.R (VSheaf.direct_image_locale f L.R)) p g.f# = h.f#) \elim q
      | idp => (idp,idp)

    \lemma eqCast {L M : RingedLocale} {f : LocaleHom L M} {g h : RingedLocaleHom L M f} (q : g = {RingedLocaleHom L M} h) : g = h
      => \have s => eqSigma q
         \in Paths.Meta.ext $ rewrite (prop-pi : s.1 = idp) in s.2

    \func castOver {L M : RingedLocale} (h : RingedLocaleHom L M) {f : LocaleHom L M} (p : h.f* = f) : \Sigma (h' : RingedLocaleHom h.Dom h.Cod f) (h' = h) \elim p
      | idp => (h,idp)

    \func fromHomEq {L M : Locale} {f g : LocaleHom L M} (p : f = g) (a : M) : f a <= g a
      => transport (\lam (h : LocaleHom L M) => f a <= h a) p <=-refl

    \lemma equals {L M : RingedLocale} {f g : RingedLocaleHom L M} (p : f.f* = g.f*) (q : \Pi (a : M) (x : M.R a) -> L.R.F.Func (fromHomEq p a) (g.f# a x) = f.f# a x) : f = g
      => aux f.f# g.f# p q
      \where {
        \private \lemma aux {L M : RingedLocale} {f g : LocaleHom L M} (f# : NatTrans M.R (VSheaf.direct_image_locale f L.R)) (g# : NatTrans M.R (VSheaf.direct_image_locale g L.R)) (p : f = g) (q : \Pi (a : M) (x : M.R a) -> L.R.F.Func (fromHomEq p a) (g# a x) = f# a x) : (\new RingedLocaleHom L M f f#) = (\new RingedLocaleHom L M g g#) \elim p
          | idp => cong $ exts $ \lam a => exts (\lam x => inv (q a x) *> pmap (\lam (h : RingHom (L.R (f a)) (L.R (f a))) => h (g# a x)) (L.R.F.Func-id {f a}))
      }

    \protected \func id {L : RingedLocale} : RingedLocaleHom L L \cowith
      | f* => FrameHom.id
      | f# {
        | trans x => Cat.id _
        | natural p => ext $ pmap (\lam x => (L.R.F.Func x).func) prop-pi
      }

    \protected \func compose \alias \infixl 8 ∘ {L M N : RingedLocale} (g : RingedLocaleHom M N) (f : RingedLocaleHom L M) : RingedLocaleHom L N \cowith
      | f* => f.f* FrameHom.∘ g.f*
      | f# {
        | trans x => f.f#.trans (g x) RingHom.∘ g.f#.trans x
        | natural {x} {y} p => exts \lam x => path (\lam i => f.f# (g y) (g.f#.natural p i x)) *> path (\lam i => f.f#.natural _ i _)
      }
  }

\record LocallyRingedLocale \extends RingedLocale {
  | isLRLNonTrivial (a : L) : 0 = {R.F a} 1 -> a <= bottom
  | isLocallyRinged (a : L) (x : R.F a) : a <= Join (\lam b => \Sigma (p : b <= a) (Inv (R.F.Func p x) || Inv (R.F.Func p (x + 1))))

  \lemma locallyRinged-split_ide {a : L} {x y : R.F a} (x+y=1 : x + y = 1) : a <= Join (\lam b => \Sigma (p : b <= a) (Inv (R.F.Func p x) || Inv (R.F.Func p y)))
    => isLocallyRinged a (negative x) <=∘ Join-univ \lam {b} => \case \elim __ \with {
      | (b<=a, byLeft e) => Join-cond (b<=a, byLeft $ Ring.Inv_negative $ transport Inv AddGroupHom.func-negative e)
      | (b<=a, byRight e) => Join-cond (b<=a, byRight $ transportInv (\lam r => Inv (R.F.Func b<=a r)) (equation.abGroup {x+y=1}) e)
    }

  \lemma locallyRinged-split_Inv {a : L} {x y : R.F a} (x+y-inv : Inv (x + y)) : a <= Join (\lam b => \Sigma (p : b <= a) (Inv (R.F.Func p x) || Inv (R.F.Func p y)))
    => locallyRinged-split_ide {_} {a} {x * x+y-inv.inv} {y * x+y-inv.inv} (inv Ring.rdistr *> x+y-inv.inv-right) <=∘ Join-univ \lam {b} => \case \elim __ \with {
      | (b<=a, byLeft e) => Join-cond (b<=a, byLeft $ Inv.cfactor-left $ transport Inv func-* e)
      | (b<=a, byRight e) => Join-cond (b<=a, byRight $ Inv.cfactor-left $ transport Inv func-* e)
    }

  \type IsAffineOpen (a : L) => Given
    (∀ (x : R a) ∃ (b : L) (p : b <= a) (Localization (SubMonoid.powers x) (R b) (R.F.Func p)))
    (∀ {b} (p : b <= a) (b <= Join \lam c => Given (q : c <= b) ∃ (x : R a) (Localization (SubMonoid.powers x) (R c) (R.F.Func (q <=∘ p)))))

  \func IsAffineScheme : \Prop
    => IsAffineOpen top
}

\record LocallyRingedLocaleHom.{s} \extends RingedLocaleHom.{s} {
  \override Dom : LocallyRingedLocale.{s}
  \override Cod : LocallyRingedLocale.{s}

  | isLRLHomLocal {c : Dom} {a : Cod} (c<=fa : c <= f* a) {x : Cod.R a} : Inv (Dom.R.F.Func c<=fa (f# a x)) ->
      c <= CompleteLattice.SJoin f* \lam b => \Sigma (b<=a : b <= a) (Inv (Cod.R.F.Func b<=a x))
} \where {
  \protected \lemma equals {L M : LocallyRingedLocale} {f g : LocallyRingedLocaleHom L M}
                           (p1 : \Pi (a : M) -> f.f* a <= g.f* a) (p2 : \Pi (a : M) -> g.f* a <= f.f* a)
                           (q : \Pi (a : M) -> L.R.F.Func (p1 a) RingHom.∘ g.f# a = f.f# a) : f = g
    => aux (exts \lam a => <=-antisymmetric (p1 a) (p2 a)) \lam a x => pmap (L.R.F.Func __ _) prop-pi *> path \lam i => q a i x
    \where {
      \private \lemma aux {f* g* : LocaleHom L M} (p : f* = g*) {f : LocallyRingedLocaleHom L M f*} {g : LocallyRingedLocaleHom L M g*}
                          (q : \Pi (a : M) (x : M.R a) -> L.R.F.Func (=_<= (path \lam i => p i a)) (g.f# a x) = f.f# a x) : f = g \elim p
        | idp => ext (idp, simp_coe $ simp_coe \lam a => exts \lam x => inv (q a x) *> path \lam i => L.R.F.Func-id i _)
    }

  \protected \func id {L : LocallyRingedLocale} : LocallyRingedLocaleHom L L \cowith
    | RingedLocaleHom => RingedLocaleHom.id {L}
    | isLRLHomLocal ca xi => CompleteLattice.SJoin-cond $ later (ca, xi)

  \protected \func compose \alias \infixl 8 ∘ {L M N : LocallyRingedLocale} (g : LocallyRingedLocaleHom M N) (f : LocallyRingedLocaleHom L M) : LocallyRingedLocaleHom L N \cowith
    | RingedLocaleHom => g RingedLocaleHom.∘ f
    | isLRLHomLocal {c} {a} => unfold \lam c<=fga {x} xi => f.isLRLHomLocal c<=fga xi <=∘ L.L.SJoin-univ (later
      \lam {b} (b<=ga,xi') => func-<= (g.isLRLHomLocal b<=ga xi') <=∘ f.f*.func-SJoin>= <=∘ L.L.SJoin-univ \lam {a'} s => L.L.SJoin-cond s)
}

\record LocallyRingedSite.{s} (\coerce P : PreorderSite.{s}) (R : Functor P.op CRingBicat.{s}) (R-sheaf : IsPreorderSheaf R) {
  | isNonTrivialPres (a : P) : 0 = {R a} 1 -> Cover a empty
  | isLocallyRingedPres (a : P) (x : R a) : Cover a (\lam b => \Sigma (p : b <= a) (Inv (R.Func p x) || Inv (R.Func p (x + 1))))

  \lemma R-equals {a : P} {U : Set P} (a<=U : Cover a U) {x y : R a} (p : ∀ {b} {c : U} (ba : b <= a) (b <= c) (R.Func ba x = R.Func ba y)) : x = y
    => path \lam i => (IsSheaf.makeSheaf (sheaf-preserve CRingCat.forget CRingCat.forget.preservesLimit (IsPreorderSheaf.makeSheaf R-sheaf))).separated-covering
        (Cover.toCovering a<=U) {\Sigma} {\lam _ => x} {\lam _ => y} (\lam {u} (inP (z,Uz,u<=z)) => exts \lam _ => p Uz u.2 u<=z) i ()

  \protected \func toLocale : LocallyRingedLocale \cowith
    | L => SiteLocale P
    | R => SiteLocaleSheaf R R-sheaf
    | isLRLNonTrivial U p {x} Ux => Cover.cover-sub (isNonTrivialPres x $ pmap (__.1 (x,Ux)) p) empty-univ
    | isLocallyRinged U a {x} Ux =>
      \let proj => (extend {_} {CRingBicat}).Func (embed-univ Ux)
      \in Cover.cover-sub (isLocallyRingedPres x ((extend.lim {_} {CRingBicat} (embed x)).coneMap (x, Cover.cover-refl idp) (proj a))) \lam {y} s => inP (embed y, (embed-univ $ U.2 $ cover-inj s.1 Ux, \case s.2 \with {
        | byLeft ai => byLeft $ (embedProj {_} {CRingBicat} y).equiv-Inv (CRingCat.Iso<->IsEquiv.1 (embed-iso R-sheaf)) $ transport Inv (a.2 s.1) ai
        | byRight ai => byRight $ (embedProj {_} {CRingBicat} y).equiv-Inv (CRingCat.Iso<->IsEquiv.1 (embed-iso R-sheaf)) $ transport Inv (func-+ *> pmap (_ +) func-ide *> pmap (`+ _) (a.2 s.1)) ai
      }), Cover.cover-refl idp)

  \lemma affineOpen {a : P}
    (ap : ∀ (x : R a) ∃ (b : P) (p : b <= a) (Localization (SubMonoid.powers x) (R b) (R.Func p)))
    (aq : ∀ {b} (p : b <= a) (Cover b \lam d => Given (q : d <= b) ∃ (x : R a) (Localization (SubMonoid.powers x) (R d) (R.Func (q <=∘ p)))))
    : toLocale.IsAffineOpen (embed a)
    => \let | proj c => embedProj {_} {CRingBicat} c
            | proj-eq c => CRingCat.Iso<->IsEquiv.1 (embed-iso R-sheaf {c})
       \in (\lam x => \case ap (proj a x) \with {
              | inP (b,b<=a,bl) => inP (embed b, embed-univ $ cover-inj b<=a idp, Localization.equiv-transport1.reverse (proj a) (proj-eq a) bl (proj b) (proj-eq b) \lam x => later $ path \lam i => embed-natural {_} {CRingBicat} b<=a i x)
            }, \lam {U} U<=a => element_SJoin_<= U<=a <=∘ CompleteLattice.SJoin-univ (later \lam {y} (Uy,y<=a) => embed-univ $
                Cover.cover-sub (aq y<=a) \lam {z} (z<=y, inP (x,zl)) => inP (embed z, (embed-univ $ U.2 $ cover-inj z<=y Uy,
                  inP (IsEquiv.ret (proj-eq a) x, Localization.equiv-transport1.reverse (proj a) (proj-eq a)
                    (transportInv (\lam r => Localization (powers r) _ _) (IsEquiv.f_ret (proj-eq a)) zl) (proj z) (proj-eq z)
                    \lam x => later $ path \lam i => embed-natural {_} {CRingBicat} _ i x)), Cover.cover-refl idp))
       )
} \where \open SiteLocaleSheaf