\import AG.RingedLocale
\import AG.Scheme
\import Algebra.Group
\import Algebra.Group.GroupHom
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.Localization
\import Algebra.Monoid.MonoidHom
\import Algebra.Monoid.Sub
\import Algebra.Pointed
\import Algebra.Pointed.PointedHom
\import Algebra.Ring
\import Algebra.Ring.Ideal
\import Algebra.Ring.Localization
\import Algebra.Ring.RingCategory
\import Algebra.Ring.RingHom
\import Algebra.Semiring
\import Category.Functor
\import Category.Topos.Sheaf
\import Category.Topos.Sheaf.DenseExtend
\import Data.Array
\import Equiv
\import Function.Meta
\import Logic
\import Logic.Meta
\import Logic.Unique
\import Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set.Subset
\import Topology.Locale
\import Topology.Locale.PreorderSite
\open SubMonoid
\open Monoid
\open Cover

\record SchemeSite.{s} (\coerce P : Preorder.{s}) (R : Functor P.op CRingBicat.{s}) {
  | loc-restrict {a b : P} (p : b <= a) : ∃ (x : R a) (Localization (powers x) (R b) (R.Func p))
  | loc-stable {a' a b : P} (r : a' <= a) (p : b <= a) : ∃ (b' : P) (p' : b' <= a') (b' <= b) (x : R a)
    (Localization (powers x) (R b) (R.Func p)) (Localization (powers (R.Func r x)) (R b') (R.Func p'))
  | loc-exists {a : P} (x : R a) : ∃ (b : P) (p : b <= a) (Localization (powers x) (R b) (R.Func p))

  \func IsLocalizationAt {a b : P} (ba : b <= a) (x : R a) : \Prop
    => Localization (powers x) (R b) (R.Func ba)

  \lemma loc-stable-forall {a' a b : P} (r : a' <= a) (p : b <= a) {x : R a} (bx : IsLocalizationAt p x)
    : ∃ (b' : P) (p' : b' <= a') (b' <= b) (IsLocalizationAt p' (R.Func r x))
    => \have | lem {x y : R a} (bx : IsLocalizationAt p x) (by : IsLocalizationAt p y)
               : ∃ (n : Nat) (LDiv (R.Func r x) (pow (R.Func r y) n))
               => \case Localization.subMonoid-compare1 bx by \with {
                    | inP (n,x|y^n) => inP (n, LDiv.make (R.Func r x|y^n.inv) $ inv func-* *> pmap (R.Func r) x|y^n.inv-right *> MonoidHom.func-pow)
                  }
             | (inP (b',p',b'b,y,by,b'l)) => loc-stable r p
       \in inP (b', p', b'b, Localization.transportSubMonoid1 b'l (lem bx by) (lem by bx))

  \func toSite : PreorderSite \cowith
    | Preorder => P
    | isBasicCover a U => Given (0 = {R a} 1) (U = empty) || Given (x y : R a) (x + y = 1) (b c : P)
      (ba : b <= a) (ca : c <= a) (IsLocalizationAt ba x) (IsLocalizationAt ca y) (U = \lam z => (b = z) || (c = z))
    | basic-cover-stable {a'} {a} a'<=a {U} => \case \elim U, \elim __ \with {
      | _, byLeft (at,idp) => inP (_, byLeft (inv func-zro *> pmap (R.Func a'<=a) at *> func-ide, idp), Refines-refl, absurd __)
      | _, byRight (x,y,x+y=1,b,c,ba,ca,bl,cl,idp) => \case loc-stable-forall a'<=a ba bl, loc-stable-forall a'<=a ca cl \with {
        | inP (b',b'a',b'b,b'l), inP (c',c'a',c'c,c'l) => inP (_, byRight (_, _, inv func-+ *> pmap (R.Func a'<=a) x+y=1 *> func-ide, b', c', b'a', c'a', b'l, c'l, idp), \lam {x} => \case \elim x, \elim __ \with {
          | _, byLeft idp => inP (b, byLeft idp, b'b)
          | _, byRight idp => inP (c, byRight idp, c'c)
        }, \lam {t} => \case \elim t, \elim __ \with {
          | _, byLeft idp => b'a'
          | _, byRight idp => c'a'
        })
      }
    }

  \func toLRLSite : LocallyRingedSite toSite R \cowith
    | R-sheaf => IsPreorderSheaf.fromSheaf (sheaf-reflect CRingCat.forget forget.reflectsLimit (IsPreorderSheaf.toSheaf setPreorderSheaf)) __
    | isNonTrivialPres a at => cover-basic $ byLeft (at,idp)
    | isLocallyRingedPres a x => \case loc-exists (negative x), loc-exists (x + 1) \with {
      | inP (b,ba,bl), inP (c,ca,cl) => cover-trans (byRight (negative x, x + 1, equation.abGroup, b, c, ba, ca, bl, cl, idp))
        \lam {t} e => cover-refl \case \elim t, \elim e \with {
          | _, byLeft idp => (ba, byLeft $ Ring.Inv_negative $ transport Inv AddGroupHom.func-negative $ bl.localization-inv $ inP (1, ide-left))
          | _, byRight idp => (ca, byRight $ cl.localization-inv $ inP (1, ide-left))
        }
    }
    \where {
      \private \lemma setPreorderSheaf : IsPreorderSheaf {toSite} (Comp forget.{s} R)
        => \lam {a} {S} a<=S _ {D} => IsPreorderSheaf.SetSheafCond a S \case \elim S, \elim a<=S \with {
          | _, byLeft (at,idp) => contr-equiv (pi-Contr _ \lam _ => Ring.trivial-char.1 at) $ later \new Contr {
            | center => \new MatchingFamily {
              | family j => \case j.2
              | isMatching {j} => \case j.2
            }
            | contraction mf => exts \lam j => \case j.2
          }
          | _, byRight (x,y,x+y=1,b,c,ba,ca,bl,cl,idp) => IsEquiv.fromInjSurj
            (\lam {h} {h'} p => ext \lam _ => localization-merge-unique x+y=1 bl cl
              (path \lam i => p i ((b,ba), byLeft idp) ()) (path \lam i => p i ((c,ca), byRight idp) ()))
            \lam mf => \case loc-stable-forall ba ca cl \with {
              | inP (d,db,dc,dl) => \case localization-merge x+y=1 bl cl dl (R.Func dc)
                    (\lam z => inv (path \lam i => R.Func-o i z) *> pmap (R.Func __ z) prop-pi *> path \lam i => R.Func-o i z)
                    (path \lam i => mf.isMatching prop-pi i ()) \with {
                | inP (r,q1,q2) => inP (\lam _ => r, later $ exts \lam j =>
                  \have je : (j = ((b,ba), byLeft idp)) || (j = ((c,ca), byRight idp)) => \case \elim j \with {
                    | ((_,t), byLeft idp) => byLeft $ ext (ext idp)
                    | ((_,t), byRight idp) => byRight $ ext (ext idp)
                  }
                  \in \case \elim j, \elim je \with {
                    | _, byLeft idp => ext \lam _ => q1
                    | _, byRight idp => ext \lam _ => q2
                  })
              }
            }
        }
    }

  \protected \func toLocale : Locale
    => SiteLocale toSite

  \sfunc Func-Cover1 {b a : P} (b<=a : Cover1 {toSite} b a) : RingHom (R a) (R b)
    => (SiteLocaleSheaf.cover-restrict {toSite} toLRLSite.R-sheaf b<=a).1
    \where {
      \protected \lemma char (ba : Cover1 {toSite} b a) {c : P} (cb : c <= b) (ca : c <= a) {x : R a} : R.Func cb (Func-Cover1 ba x) = R.Func ca x
        => rewrite (\peval Func-Cover1 ba) $ path \lam i => (SiteLocaleSheaf.cover-restrict {toSite} toLRLSite.R-sheaf ba).2 cb ca i x
    }

  \lemma Func-Cover1_<= {b a : P} {ba : b <= a} {x : R a} : Func-Cover1 (cover-inj ba idp) x = R.Func ba x
    => inv (path \lam i => R.Func-id i _) *> pmap (\lam r => R.Func _ (Func-Cover1 r x)) prop-pi *> Func-Cover1.char (cover-inj ba idp) <=-refl ba

  \lemma Func-Cover1-o {c b a : P} {cb : Cover1 {toSite} c b} {ba : Cover1 {toSite} b a} {x : R a}
    : Func-Cover1 cb (Func-Cover1 ba x) = Func-Cover1 (cover-trans1 cb ba) x
    => toLRLSite.R-equals cb \lam {d} {_} (idp) d<=c d<=b => Func-Cover1.char cb d<=c d<=b *>
        toLRLSite.R-equals (cover-left d<=b ba) \lam {e} {_} (idp) e<=d e<=a => inv (path \lam i => R.Func-o i _) *>
        Func-Cover1.char _ _ e<=a *> inv (Func-Cover1.char _ _ e<=a) *> path (\lam i => R.Func-o i _)

  \lemma loc-principal {a b : P} {ba : b <= a} {x : R a} : toLRLSite.IsPrincipalOpenAt ba x <-> IsLocalizationAt ba x
    => (\lam xp => \case loc-exists x, loc-restrict ba \with {
      | inP (c,ca,cl), inP (y,by) => Localization.equiv-transport2 cl by
        (Localization.liftHom1 cl (R.Func ba) xp.1) (\lam y => cl.lift_inL) (Func-Cover1 $ xp.2 ca $ cl.localization-inv powers-id)
        \lam y => pmap (Func-Cover1 _) (inv Func-Cover1_<=) *> Func-Cover1-o *> pmap (Func-Cover1 __ y) prop-pi *> Func-Cover1_<=
    }, \lam bl => (bl.localization-inv powers-id, \lam ca => inv-cover ba ca bl))

  \lemma basis-affineOpen {a : P} : toLRLSite.toLocale.IsAffineOpen (SiteLocale.embed a)
    => toLRLSite.affineOpen
      (\lam x => \case loc-exists x \with {
        | inP (b,ba,bl) => inP (b, ba, loc-principal.2 bl)
      })
      (\lam {b} ba x bp {U} b<=U =>
        \let (inP (_, inP (n,idp), Wx)) => (LocalizationIdeal.unit-char {Ideal.sclosure _} (loc-principal.1 bp)).1 $
              (LocalizationIdeal.sclosure-char (loc-principal.1 bp)).2 $ Ideal.sclosure-univ {_} {_} {Ideal.sclosure _}
              (later \lam {y} (inP (d,c,dc,Uc,db,dl)) => \case (loc-principal.1 bp).localization-surj y \with {
                | inP (z, _, inP (n,idp), q) =>
                  \have ei => (loc-principal.1 bp).localization-inv (inP (suc n, idp))
                  \in transportInv (Ideal.sclosure _) (ei.rotate-inv-right $ pmap (y *) func-* *> inv *-assoc *> pmap (`* _) q *> *-comm *> inv func-*) $
                      ideal-right $ Ideal.sclosure-superset $ SetIm-con $ inP $ later (c, Uc, d, dc, db,
                        transportInv (Localization _ _) R.Func-o $ Localization.comp1 (loc-principal.1 bp) $ Localization.transportSubMonoid1 dl
                        (inP (1, LDiv.make _ $ inv (((loc-principal.1 bp).localization-inv (inP (n, idp))).rotate-inv-right q) *> inv ide-left))
                        (inP (1, LDiv.make _ $ q *> inv ide-left)))
              }) (Cover_Ideal b<=U)
        \in inP (n, Wx))
      (\lam ba => \case loc-restrict ba \with {
        | inP (x,bl) => cover-refl (<=-refl, inP (x, loc-principal.2 $ transport (IsLocalizationAt __ x) prop-pi bl))
      })

  \lemma top-affine {t : P} (tt : \Pi (x : P) -> x <= t) : toLRLSite.toLocale.IsAffineScheme
    => transport toLRLSite.toLocale.IsAffineOpen (<=-antisymmetric top-univ $ later \lam {x} _ => cover-inj (tt x) idp) $ basis-affineOpen {_} {t}

  \func toScheme : Scheme \cowith
    | LocallyRingedLocale => toLRLSite.toLocale
    | isLocallyAffine {x} _ => cover-refl $ inP (SiteLocale.embed x, basis-affineOpen, cover-refl idp)

  \lemma inv-cover {a b c : P} (ca : c <= a) (ba : b <= a) {x : R a} (cl : IsLocalizationAt ca x) (xb : Inv (R.Func ba x)) : Cover1 {toSite} b c
    => \case loc-stable-forall ba ca cl \with {
      | inP (d,db,dc,dl) => \case loc-exists {_} {d} 0 \with {
        | inP (t,td,tl) => cover-trans (byRight (1, 0, zro-right, d, t, db, td <=∘ db,
          Localization.transportSubMonoid1 dl (inP (1, LDiv.ide-div)) (inP (1, transportInv (LDiv _) ide-left xb)),
          (Localization.trivial1 Ring.zro_*-left).2 $ (Localization.trivial1 Ring.zro_*-left).1 tl, idp)) \lam {r} => \case \elim r, \elim __ \with {
            | _, byLeft idp => cover-inj dc idp
            | _, byRight idp => cover-inj (td <=∘ dc) idp
          }
      }
    }

  \lemma inv-cover1 {a b c : P} (ca : c <= a) (ba : Cover1 {toSite} b a) {x : R a} (cl : IsLocalizationAt ca x) (xb : Inv (Func-Cover1 ba x)) : Cover1 {toSite} b c
    => cover-trans* (cover-down ba) \lam {b'} (inP (_,idp,b'<=a,b'<=b)) => inv-cover ca b'<=a cl $ transport Inv (Func-Cover1.char _ _ _) $ (R.Func b'<=b).func-Inv xb

  \lemma Cover_Ideal {a : P} {U : Set P} (a<=U : Cover {toSite} a U)
    : Ideal.sclosure (\lam x => ∃ (b c : P) (b <= c) (U c) (ba : b <= a) (IsLocalizationAt ba x)) 1 \elim a<=U
    | cover-inj {t} a<=t Ut => Ideal.sclosure-superset $ inP $ later (a, t, a<=t, Ut, <=-refl, transportInv (Localization _ _) R.Func-id Localization.id1)
    | cover-trans (byLeft (at,idp)) _ => rewriteI at (Ideal.sclosure _).contains_zro
    | cover-trans (byRight (x,y,x+y=1,b,c,b<=a,c<=a,bx,cy,idp)) bc<=U =>
      \let | I a => Ideal.sclosure \lam x => ∃ (b c : P) (b <= c) (U c) (ba : b <= a) (IsLocalizationAt ba x)
           | lem {d} (da : d <= a) {z} (dl : IsLocalizationAt da z) : I d ⊆ LocalizationIdeal (I a) (R.Func da) dl
             => Ideal.sclosure-univ {_} {_} {LocalizationIdeal (I a) _ dl} (hiding (I,x+y=1,bc<=U,a,U,x,y,b,c,bx,cy,b<=a,c<=a) $ later \lam {y} (inP (b,c,bc,Uc,bd,bl)) => \case dl.localization-surj y \with {
               | inP (r, _, inP (n,idp), q) => inP (_, inP (suc n, idp), z * r, Ideal.sclosure-superset $ inP $ later (b, c, bc, Uc, bd <=∘ da,
                    transportInv (Localization _ _) R.Func-o $ Localization.comp1 dl $ Localization.transportSubMonoid1 bl
                      (inP (1, LDiv.make (dl.localization-inv (inP (n,idp))).inv $ pmap (`* _) (inv q) *> *-assoc *> pmap (y *) LDiv.inv-right *> ide-right *> inv ide-left))
                      (inP (1, LDiv.make _ $ q *> inv ide-left))),
                  pmap (y *) func-* *> inv *-assoc *> pmap (`* _) q *> *-comm *> inv func-*)
             }) __
           | (inP (_, inP (n,idp), Ix^n)) => (LocalizationIdeal.unit-char {I a} bx).1 $ lem b<=a bx $ Cover_Ideal (bc<=U (byLeft idp))
           | (inP (_, inP (m,idp), Iy^m)) => (LocalizationIdeal.unit-char {I a} cy).1 $ lem c<=a cy $ Cover_Ideal (bc<=U (byRight idp))
           | (inP (t,s,tx^n+sy^m=1)) => pow-lin-comb1 x+y=1 n m
      \in transport (I a) tx^n+sy^m=1 $ (I a).contains_+ ((I a).ideal-left Ix^n) ((I a).ideal-left Iy^m)

  {-
  \lemma cover-sum {a : P} {x y : R a} {b c d : P} (ba : b <= a) (ca : c <= a) (da : d <= a)
                   (bl : IsLocalizationAt ba (x + y)) (cl : IsLocalizationAt ca x) (dl : IsLocalizationAt da y)
    : Cover {toSite} b \lam z => (c = z) || (d = z)
    => \case loc-stable-forall ba ca cl, loc-stable-forall ba da dl \with {
      | inP (c',c'b,c'c,c'x), inP (d',d'b,d'd,d'y) =>
        \let x+y-inv => bl.localization-inv powers-id
        \in cover-trans (byRight (R.Func ba x * x+y-inv.inv, R.Func ba y * x+y-inv.inv, inv rdistr *> pmap (`* _) (inv func-+) *> x+y-inv.inv-right,
                                  c', d', c'b, d'b, {?}, {?}, idp)) {?}
    }
  -}

  \lemma cover-div {a : P} {x y : R a} (y|x : LDiv y x) {b c : P} (ba : b <= a) (ca : c <= a)
                   (bl : IsLocalizationAt ba x) (cl : IsLocalizationAt ca y) : Cover1 {toSite} b c
    => inv-cover ca ba cl $ Inv.Inv_LDiv (bl.localization-inv powers-id) $ (R.Func ba).func-LDiv y|x

  \lemma cover-BigSum {a : P} {n : Nat} {l : Array (R a) n} (p : AddMonoid.BigSum l = 1) {U : Set P}
                      (lU : ∀ (x : l) ∃ (b : P) (Cover {toSite} b U) (ba : b <= a) (IsLocalizationAt ba x)) : Cover {toSite} a U \elim n, l
    | 0, nil => cover-trans (byLeft (p, idp)) \case __
    | suc n, x :: l => \case lU 0, loc-exists (AddMonoid.BigSum l) \with {
      | inP (b,b<=U,ba,bl), inP (c,ca,cl) => cover-trans (byRight (x, AddMonoid.BigSum l, p, b, c, ba, ca, bl, cl, idp)) \lam {e} => \case \elim e, \elim __ \with {
        | _, byLeft idp => b<=U
        | _, byRight idp =>
          \let xi => cl.localization-inv powers-id
          \in cover-BigSum {_} {c} {n} (inv Semiring.BigSum-rdistr *> pmap (`* _) (inv AddMonoidHom.func-BigSum) *> xi.inv-right)
            \lam j => \case lU (suc j) \with {
              | inP (d,d<=U,da,dl) => \case loc-stable-forall ca da dl \with {
                | inP (d',d'c,d'd,d'l) => inP (d', cover-left d'd d<=U, d'c, Localization.transportSubMonoid1 d'l (inP (1, LDiv.make _ $ *-assoc *> pmap (_ *) xi.inv-left *> ide-right *> inv ide-left)) (inP (1, LDiv.make xi.inv $ inv ide-left)))
              }
            }
      }
    }

  \lemma Ideal_Cover {a : P} {U : Set P} (c : Ideal.sclosure (\lam x => ∃ (b : P) (c : U) (b <= c) (ba : b <= a) (IsLocalizationAt ba x)) 1) : Cover {toSite} a U \elim c
    | inP (l,p) => cover-BigSum (inv p) \lam j => \case (l j).2.2, loc-exists ((l j).1 * (l j).2.1) \with {
      | inP (b,c,Uc,bc,ba,bl), inP (d,da,dl) => inP (d, cover-trans1 (cover-div (LDiv.make _ *-comm) da ba dl bl) $ cover-inj bc Uc, da, dl)
    }
} \where {
  \open CRingCat(forget)

  \lemma pow-lin-comb {R : CRing} (x y : R) (n m : Nat) : ∃ (t s : R) (k : Nat) (pow (x + y) k = t * pow x n + s * pow y m) \elim n
    | 0 => inP (1, 0, 0, simplify)
    | suc n => \case pow-lin-comb x y n m, sum-factor m \with {
      | inP (t,s,k,p), inP (c,q) => inP (t * c, pow (x + y) k + s * c * x, k Nat.+ m, pow_+ *> equation.cRing {p,q})
    }
    \where {
      \protected \lemma sum-factor (m : Nat) : ∃ (c : R) (pow (x + y) m = c * x + pow y m) \elim m
        | 0 => inP (0, simplify)
        | suc m => \case sum-factor m \with {
          | inP (c,p) => inP (c * y + pow (x + y) m, equation.cRing {p})
        }
    }

  \lemma pow-lin-comb1 {R : CRing} {x y : R} (x+y=1 : x + y = 1) (n m : Nat) : ∃ (t s : R) (t * pow x n + s * pow y m = 1)
    => \case pow-lin-comb x y n m \with {
      | inP (t,s,k,p) => inP (t, s, inv p *> pmap (pow __ k) x+y=1 *> pow_ide)
    }

  \lemma localization-merge-unique {R : CRing} {x0 y0 : R} (x0+y0=1 : x0 + y0 = 1) (A : Localization (powers x0)) (B : Localization (powers y0))
                                   {x y : R} (Axy : A x = A y) (Bxy : B x = B y) : x = y
    => \case localization-inj Axy, localization-inj Bxy \with {
      | inP (_, inP (n,idp), p), inP (_, inP (m,idp), q) => \case pow-lin-comb1 x0+y0=1 n m \with {
        | inP (t,s,r) => equation.cRing {inv r, p, q}
      }
    }

  \lemma localization-merge {R : CRing} {x y : R} (x+y=1 : x + y = 1)
                            (A : Localization (powers x)) (B : Localization (powers y))
                            (T : Localization (powers (A y))) (S : MonoidHom B.L T.L) (coh : \Pi (z : R) -> T (A z) = S (B z))
                            {a : A} {b : B} (Ta=Sb : T a = S b) : ∃ (r : R) (A r = a) (B r = b)
    => \have | (inP (a', _, inP (n,idp), ax^n=a')) => localization-surj a
             | (inP (b', _, inP (m,idp), by^m=b')) => localization-surj b
             | am : T (A (a' * pow y m)) = T (A (b' * pow x n))
                  => pmap T (func-* *> pmap (`* _) (inv ax^n=a')) *> func-* *> pmap (`* _) func-* *> *-assoc *>
                     pmap2 (*) Ta=Sb (*-comm *> pmap2 (*) (coh _) (coh _)) *> inv *-assoc *> pmap (`* _) (inv func-*) *>
                     inv func-* *> pmap S (pmap (`* _) by^m=b' *> inv func-*) *> inv (coh _)
             | (inP (_, inP (k,idp), p)) => (Localization.comp1 A T).localization-inj am
             | (inP (t,s,q)) => pow-lin-comb1 x+y=1 (n Nat.+ k) (m Nat.+ k)
       \in rewrite R.pow_*-comm at p $ rewrite (pow_+,pow_+) at q $
           inP (t * a' * pow x k + s * b' * pow y k,
                (A.localization-inv (inP (n,idp))).inv-cancel-right $ inv func-* *> (A.localization-inv (inP (k,idp))).inv-cancel-right
                  (inv func-* *> pmap A (equation.cRing {inv p, q}) *> func-*) *> inv ax^n=a',
                (B.localization-inv (inP (m,idp))).inv-cancel-right $ inv func-* *> (B.localization-inv (inP (k,idp))).inv-cancel-right
                  (inv func-* *> pmap B (equation.cRing {p, q}) *> func-*) *> inv by^m=b')
}

\func LRL->SchemeSite {L : RingedLocale} (C : L -> \Prop) (Ca : ∀ {a : C} (L.IsAffineOpen a))
    (Cc : ∀ {a : C} {b} (ba : b <= a) {x : L.R a} (L.IsPrincipalOpenAt ba x) (C b)) : SchemeSite \cowith
  | P => preorder
  | R => Comp L.R embedding.op
  | loc-restrict {a} ba => \case ba.2 \with {
    | inP r => inP (r.1, transport (Localization _ _) (pmap Func prop-pi) $ L.principal-localization (Ca a.2) r.2)
  }
  | loc-stable {a'} {a} {b} (a'<=a, inP (y,yl)) (b<=a, inP (x,xl)) =>
    \have xp => L.principal_meet-left a'<=a b<=a xl
    \in inP ((a'.1 ∧ b.1, Cc a'.2 meet-left xp), (meet-left, inP (_, xp)), (meet-right, inP (_, L.principal_meet-right a'<=a yl b<=a)),
             x, transport (Localization _ _) (pmap L.R.F.Func prop-pi) $ L.principal-localization (Ca a.2) xl,
             transport (\lam r => Localization (powers (L.R.F.Func r x)) _ _) prop-pi $ L.principal-localization (Ca a'.2) xp)
  | loc-exists {a} x => inP ((L.principalOpen x, Cc a.2 L.principalOpen_<= {x} L.principalOpen-principal),
    (L.principalOpen_<=, inP (x, L.principalOpen-principal)), L.principal-localization (Ca a.2) L.principalOpen-principal)
  \where {
    \func preorder : Preorder \cowith
      | E => \Sigma (a : L) (C a)
      | <= a b => Given (p : a.1 <= b.1) ∃ (x : L.R b.1) (L.IsPrincipalOpenAt p x)
      | <=-refl => (<=-refl, inP (1, L.principal-id))
      | <=-transitive {c} {b} {a} (cb, inP (y,yl)) (ba, inP (x,xl)) => (cb <=∘ ba, L.principal-o (Ca a.2) yl xl)

    \func embedding : PreorderHom preorder L \cowith
      | func s => s.1
      | func-<= s => s.1
  }

\func maxSchemeSite (L : RingedLocale) : SchemeSite
  => LRL->SchemeSite L.IsAffineOpen (\lam p => p) \lam aff ba => L.principal-affine aff