\import Data.Or

\class HasProduct (E : \Type)
  | Product \alias \infixl 7 ⨯ : E -> E -> E

\instance TypeHasProduct : HasProduct \Type
  | Product A B => \Sigma A B

\instance SetHasProduct : HasProduct \Set
  | Product A B => \Sigma A B

\class HasCoproduct (E : \Type)
  | Coproduct \alias \infixl 6 ⨿ : E -> E -> E

\instance TypeHasCoproduct : HasCoproduct \Type
  | Coproduct A B => Or A B

\instance SetHasCoproduct : HasCoproduct \Set
  | Coproduct A B => Or A B
