\import Category
\import Category.Functor
\import Category.Slice
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Paths
\import Paths.Meta
\import Set.Subset (Set)

\func Presieve {C : Precat} (x : C)
  => Set (ObOver x)
  \where {
    \protected \func pushforward (F : Functor) {x : F.C} (P : Presieve x) : Presieve (F x)
      => \lam py => ∃ (px : P) (py = (F px.1, Func px.2)) -- (f : Hom py.1 (F px.1)) (py.2 = Func px.2 ∘ f)
  }

\class Site \extends Precat {
  | isCover (x : Ob) : Presieve x -> \Prop
  | cover-stable {x y : Ob} (h : Hom x y) : ∀ {S : isCover y} ∃ (T : isCover x) ∀ (px : T) ∃ (py : S) (f : Hom px.1 py.1) (py.2 ∘ f = h ∘ px.2)

  \func IsCoverFam {J : \Sort} {x : Ob} (f : J -> ObOver x) : \Prop
    => isCover x \lam px => ∃ (j : J) (px = f j)

  \func isCover_IsCoverFam {x : Ob} {P : Presieve x} : isCover x P <-> IsCoverFam {_} {Given P} __.1
    => <->_=.2 $ pmap (isCover x) $ ext \lam px => ext (\lam Ppx => inP ((px,Ppx),idp), \lam (inP (j,p)) => transportInv P p j.2)
} \where {
  \func pushforwardFam.{o1,h1,o2,h2} {C : Site.{o1,h1}} {D : Site.{o2,h2}} (F : Functor C D) {J : \Sort} {x : C} (P : J -> ObOver x) : J -> ObOver (F x)
    => \lam j => (F (P j).1, Func (P j).2)
}

\record SiteHom.{o1,h1,o2,h2} \extends Functor.{o1,h1,o2,h2} {
  \override C : Site.{o1,h1}
  \override D : Site.{o2,h2}

  | Func-cover {x : C} {P : Presieve x} : isCover x P -> isCover (F x) (Presieve.pushforward \this P)
  | Func-flat {x y1 y2 : C} (p1 : Hom y1 x) (p2 : Hom y2 x) {u : D} (t1 : Hom u (F y1)) (t2 : Hom u (F y2)) : Func p1 ∘ t1 = Func p2 ∘ t2
    -> ∃ (w : C) (s1 : Hom w y1) (s2 : Hom w y2) (p1 ∘ s1 = p2 ∘ s2) (g : Hom u (F w)) (Func s1 ∘ g = t1) (Func s2 ∘ g = t2)

  \lemma Func-coverFam {J : \Sort} {x : C} {f : J -> ObOver x} (fc : Site.IsCoverFam f) : Site.IsCoverFam (Site.pushforwardFam \this f)
    => transport (isCover _) (ext \lam py => ext (\lam (inP (_, inP (j,idp), p)) => inP (j,p), \lam (inP (j,p)) => inP (f j, inP (j,idp), p))) (Func-cover fc)
} \where {
  \func id.{o,h} {C : Site.{o,h}} : SiteHom C C \cowith
    | Functor => Id
    | Func-cover {x} {P} => transport (isCover x) (ext \lam px => ext (\lam Ppx => inP (px,Ppx,idp), \lam (inP (py,Ppy,q)) => transportInv P q Ppy))
    | Func-flat p1 p2 {u} t1 t2 r => inP (u, t1, t2, r, Precat.id u, id-right, id-right)
}