\import AG.RingedLocale
\import Algebra.Ring.RingCategory
\import Algebra.Ring.RingHom
\import Category
\import Category.Functor
\import Category.Topos.Sheaf
\import Equiv
\import Function.Meta
\import Logic
\import Meta
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Topology.Locale
\import Topology.Locale.LocaleCat

\func RingedLocalePrecat.{s} : Precat RingedLocale.{s} \cowith
  | Hom => RingedLocaleHom
  | id (L : RingedLocale.{s}) : RingedLocaleHom L L \cowith {
    | f => FrameHom.id
    | f# => \new NatTrans {
      | trans x => Cat.id _
      | natural p => ext $ pmap (\lam x => (L.R.F.Func x).func) prop-pi
    }
  }
  | o {L M N : RingedLocale.{s}} (g : RingedLocaleHom M N) (f : RingedLocaleHom L M) : RingedLocaleHom L N \cowith {
    | f => f.f FrameHom.∘ g.f
    | f# => \new NatTrans {
      | trans x => f.f#.trans (g x) ∘ g.f#.trans x
      | natural {x} {y} p => exts \lam x => path (\lam i => f.f# (g y) (g.f#.natural p i x)) *> path (\lam i => f.f#.natural _ i _)
    }
  }
  | id-left => idp
  | id-right => idp
  | o-assoc => idp
  \where {
    \func forget : Functor RingedLocalePrecat LocaleCat \cowith
      | F L => L
      | Func f => f
      | Func-id => idp
      | Func-o => idp
  }

\instance RingedLocaleCat : Cat RingedLocale
  | Precat => RingedLocalePrecat
  | univalence => Cat.makeUnivalenceFromPath \lam e =>
    \have sip => SIP-comb LocaleCat (\lam L => (VSheafCat CRingCat L).op) (\lam L => RingedLocale L) (RingedLocaleHom __ __)
      (\lam h => Iso {RingedLocalePrecat} h) (\lam {L} {R} => RingedLocalePrecat.id R) (\lam {L} {R} => idIso)
      (\lam {L} => \new Embedding {
        | f R => R.R
        | isEmb R R' => \new Retraction {
          | sec p => ext p
          | f_sec => idpe
        }
      })
      (\lam {L} {R1} {R2} f fi => Iso.op {fromIso f $ ring-iso fi})
      (\lam {L} {R} => idp)
      (\lam {L} {R1} {R2} f g fi gi p => ext $ exts \lam x => later $ inv id-left *> path (\lam i => p i x) *> id-left)
      (RingedLocalePrecat.forget.Func-iso e) e.dom e.cod e.f e
    \in (sip.2, sip.4)
    \where {
      \func fromIso {L : Locale} {R1 R2 : RingedLocale L} (f : RingedLocaleHom R1 R2 (id L)) (e : \Pi (x : L) -> Iso (f.f# x)) : Iso {VSheafCat CRingCat L} {R2.R} {R1.R}
        => VSheafCat.functor-iso {_} {_} {R2.R} {R1.R} $ FunctorPrecat.fromIso {_} {_} {R2.R} (later \new NatTrans {
          | trans => f.f#
          | natural h => f.f#.natural h *> pmap (Func __ ∘ _) prop-pi
        }) \lam {x} => e x

      \lemma ring-iso {L : Locale} {R1 R2 : RingedLocale L} {f : RingedLocaleHom R1 R2 (id L)} (e : Iso {RingedLocalePrecat} f) (a : R2) : Iso (f.f# a)
        => \have | ei=id => inv FrameCat.id-left *> path (\lam i => (e.hinv_f i).f)
                 | gp : \Sigma (g : RingedLocaleHom R2 R1 (id L)) (g = e.hinv) => RingedLocaleHom.castOver e.hinv ei=id
                 | fg => RingedLocaleHom.eqCast $ pmap (f RingedLocalePrecat.∘) gp.2 *> e.f_hinv
                 | gf => RingedLocaleHom.eqCast $ pmap (RingedLocalePrecat.`∘ f) gp.2 *> e.hinv_f
           \in \new Iso {
            | hinv => gp.1.f# a
            | hinv_f => path (\lam i => (fg i).f# a)
            | f_hinv => path (\lam i => (gf i).f# a)
          }
    }