\import Paths
\import Paths.Meta
\import Equiv
\import Equiv.Path

\func =-to-Equiv {A B : \hType} (p : A = B) : Equiv {A} {B} => rewriteI p idEquiv

\func Equiv-to-= {A B : \hType} (e : Equiv {A} {B}) : A = B => QEquiv_= (QEquiv.fromEquiv e)

\func univalence {X Y : \hType} : QEquiv {X = Y} {Equiv {X} {Y}}
  => pathEquiv (Equiv {__} {__}) (\lam {A} {B} =>
      \new Retraction {
        | f => =-to-Equiv
        | sec => Equiv-to-=
        | f_sec e => Equiv.equals (Jl (\lam _ p => Equiv.f {=-to-Equiv p} = (\lam a => coe (p @) a right)) idp (Equiv-to-= e))
      })

