\import Homotopy.Pointed
\import Homotopy.Pushout

\func Susp (A : \hType) => PushoutData {A} (\lam _ => ()) (\lam _ => ())
  \where {
    \func rec {A B : \hType} (b1 b2 : B) (f : A -> b1 = b2) (x : Susp A) : B \elim x
      | north => b1
      | south => b2
      | pglue a => f a

    \func pointed (A : \hType) => \new Pointed (Susp A) north

    \func pushout (A : \hType) => pushoutData {A} (\lam _ => ()) (\lam _ => ())
  }

\cons north {A : \hType} : Susp A => pinl ()

\cons south {A : \hType} : Susp A => pinr ()

\func pmerid {A : \hType} (a : A) : north = south => path (pglue a)
