\import AG.RingedLocale
\import AG.RingedLocale.RingedLocaleCat
\import AG.SchemeSite
\import AG.SchemeSite.SchemeSiteHom
\import Algebra.Ring.RingHom
\import Category
\import Category.Functor
\import Category.Topos.Sheaf
\import Category.Topos.Sheaf.DenseExtend
\import Equiv
\import Function.Meta
\import Logic
\import Meta
\import Order.Lattice.CompleteLattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Topology.Locale.PreorderSite
\open SchemeSitePrehom
\open SchemeSiteHom
\open Cover

\func SchemeSitePrehomPrecat : Precat SchemeSite \cowith
  | Hom => SchemeSitePrehom
  | id _ => SchemeSitePrehom.id
  | o => SchemeSitePrehom.∘
  | id-left {_} {_} {f} => SchemeSitePrehom.equals (\lam b a => (\lam (inP (b',b<=b',b'<=a)) => <=f*-right b<=b' b'<=a, \lam b<=a => inP (a, b<=a, <=-refl)))
    \lam a b (inP (a',b<=a',a'<=a)) b<=ga x => compose.f#-eval *> f.f#_f*-right *> pmap (f.f# __ x) prop-pi
  | id-right {_} {_} {f} => SchemeSitePrehom.equals (\lam b a => (\lam (inP (b',b<=b',b'<=a)) => <=f*-left b<=b' b'<=a, \lam b<=a => inP (b, <=-refl, b<=a)))
    \lam a b (inP (b',b<=b',b'<=a)) b<=ga x => compose.f#-eval *> f.f#_f*-left *> pmap (f.f# __ x) prop-pi
  | o-assoc {_} {_} {_} {_} {h} {g} {f} => SchemeSitePrehom.equals
    (\lam x w => (\lam (inP (y, x<=y, inP (z,y<=z,z<=w))) => inP (z, inP (y, x<=y, y<=z), z<=w),
                  \lam (inP (z, inP (y,x<=y,y<=z), z<=w)) => inP (y, x<=y, inP (z, y<=z, z<=w))))
    \lam a b (inP (y, b<=y, inP (z,y<=z,z<=a))) (inP (z', inP (y',b<=y',y'<=z'), z'<=a)) x => compose.f#-eval *>
      compose.f#-coh {_} {_} {_} {h SchemeSitePrehom.∘ g} {f} {_} {_} {_} {_} {_} {_} {_} {inP (z',y'<=z',z'<=a)} *>
      pmap (SchemeSitePrehom.f# _) compose.f#-eval *> inv compose.f#-eval *> inv compose.f#-eval

\instance SchemeSitePrecat : Precat SchemeSite
  | Hom => SchemeSiteHom
  | id _ => SchemeSiteHom.id
  | o => SchemeSiteHom.∘
  | id-left => toSchemeSiteHom_o-left *> path (\lam i => (SchemeSitePrehomPrecat.id-left i).toSchemeSiteHom) *> toSchemeSiteHom-idemp
  | id-right => toSchemeSiteHom_o-right *> path (\lam i => (SchemeSitePrehomPrecat.id-right i).toSchemeSiteHom) *> toSchemeSiteHom-idemp
  | o-assoc => toSchemeSiteHom_o-left *> path (\lam i => (SchemeSitePrehomPrecat.o-assoc i).toSchemeSiteHom) *> inv toSchemeSiteHom_o-right

\func SchemeSiteFunctor : FullyFaithfulFunctor SchemeSitePrecat LocallyRingedLocaleCat \cowith
  | F S => S.toScheme
  | Func f => f.toLRLSchemeSiteHom.toLRLHom
  | Func-id {X} => later (path (\lam i => (id_toLRL i).toLRLHom)) *> LRLSchemeSiteHom.LRL-equiv.f_ret _
  | Func-o {_} {_} {_} {g} {f} => path (\lam i => (toLRLSchemeSiteHom-natural i).toLRLHom) *>
    inv (path \lam i => (toLRLSchemeSiteHom_toLRLHom {_} {_} {_} {f.toLRLSchemeSiteHom} i).toLRLHom) *>
    inv (LRLSchemeSiteHom.toLRLHom-natural {_} {_} {_} {f.toLRLSchemeSiteHom.toLRLHom} {g.toLRLSchemeSiteHom})
  | isFullyFaithful => IsEquiv.trans (inP LRL-equiv) (inP LRLSchemeSiteHom.LRL-equiv)